input-output-hk/catalyst-voices

.github/ISSUE_TEMPLATE/bug_report.yaml
=> docs: add bug report template

CODE_OF_CONDUCT.md
=> docs: Add Code of conduct

.github/ISSUE_TEMPLATE/config.yml
Needed to add issues not supported by current templates.
=> feat(issues): Enable blank issues

.github/ISSUE_TEMPLATE/TASK.yml
=> docs(issues): Add Task Issue Template

LICENSE-APACHE, LICENSE-MIT, README.md
=> docs: add licenses

.config/dictionaries/project.dic, SECURITY.md
=> feat(docs): add security policy

.github/workflows/stale-branches.yml
Add remove stale branches CI job.
Closes #20
=> feat(ci): add remove stale branches

.config/dictionaries/project.dic, .github/CODEOWNERS
=> feat: add code owners, update project dic

catalyst_voices/pubspec.yaml
- update  flutter to  3.13.8
- none
- no
=> chore(frontend): update flutter to 3.13.8

README.md, catalyst-gateway/README.md, catalyst_voices/README.md, catalyst_voices/pubspec.yaml
- update READMEs
- Upgrade Flutter
=> chore: update readme, flutter version bump

.config/dictionaries/project.dic, .github/workflows/ci.yml
> e.g., Closes #123, Resolves #456  Fixes #367
> e.g., #123, #456
=> chore: adds ci

.vscode/settings.recommended.json
Updated `settings.recommended.json` file, `rust-analyzer.linkedProjects` option.
=> fix: Update settings.recommended.json file

Earthfile
- Bumped version of the `catalyst-ci` Earthly dep for `markdown-check` and `spell-check` targets
=> feat: Bump version of the cat-ci dep

docs/FLUTTER_INTEGRATION_TEST.md
Adding a note about starting chromedriver before runnin flutter web integration tests
=> docs: Fix flutter docs

catalyst_voices/ios/Podfile.lock, catalyst_voices/lib/app/view/app_content.dart, catalyst_voices/lib/app/view/app_page.dart, catalyst_voices/lib/pages/login/login_page.dart, catalyst_voices/packages/catalyst_voices_blocs/lib/src/catalyst_voices_blocs.dart, catalyst_voices/packages/catalyst_voices_blocs/lib/src/dependency/dependency.dart, catalyst_voices/packages/catalyst_voices_blocs/lib/src/dependency/dependency_provider.dart, catalyst_voices/packages/catalyst_voices_blocs/pubspec.yaml, catalyst_voices/packages/catalyst_voices_repositories/lib/src/authentication_repository.dart, melos.yaml
This PR introduces the configuration of dependency injection (DI) in our frontend application.
Closes #75 
Dependency injection is a powerful technique for achieving loose coupling between components and services, making our code more modular, testable, and maintainable. By implementing DI, we aim to improve our front-end app's overall architecture and development experience.
None
Not applicable
None
=> feat(frontend): add dependencies injection configurations

catalyst-gateway/bin/README.md, catalyst-gateway/bin/src/service/api/mod.rs, catalyst-gateway/bin/src/settings.rs
Fixes links to cat-core with corresponding links to catalyst-voices
Closes #241
Fixes links to cat-core with corresponding links to catalyst-voices
Resolves #456  Fixes #367
Fixes links to cat-core with corresponding links to catalyst-voices
> e.g., #123, #456
=> fix: links to cat-core

catalyst_voices/packages/catalyst_voices_assets/example/pubspec.yaml, catalyst_voices/packages/catalyst_voices_assets/pubspec.yaml, catalyst_voices/packages/catalyst_voices_blocs/pubspec.yaml, catalyst_voices/packages/catalyst_voices_localization/pubspec.yaml, catalyst_voices/packages/catalyst_voices_repositories/pubspec.yaml, catalyst_voices/packages/catalyst_voices_services/pubspec.yaml, catalyst_voices/packages/catalyst_voices_shared/pubspec.yaml, catalyst_voices/packages/catalyst_voices_view_models/pubspec.yaml, catalyst_voices/pubspec.yaml, catalyst_voices_packages/catalyst_analysis/example/pubspec.yaml, catalyst_voices_packages/catalyst_analysis/pubspec.yaml, melos.yaml, pubspec.yaml
- Bump Flutter to 3.19.0 and Dart to 3.3.0
- Fixes flutter integration test
=> chore: bump flutter and dart version

.config/dictionaries/project.dic, catalyst-gateway/bin/src/event_db/queries/vit_ss/fund.rs, catalyst-gateway/bin/src/service/api/registration/mod.rs, catalyst-gateway/bin/src/service/api/v1/mod.rs, catalyst-gateway/bin/src/service/common/objects/account_votes.rs, catalyst-gateway/bin/src/service/common/objects/block.rs, catalyst-gateway/bin/src/service/common/objects/fragment_status.rs, catalyst-gateway/bin/src/service/common/objects/fragments_batch.rs, catalyst-gateway/bin/src/service/common/objects/fragments_processing_summary.rs, catalyst-gateway/bin/src/service/common/objects/voter_info.rs, catalyst-gateway/bin/src/service/common/responses/resp_5xx.rs
change from `TODO(name) : <link>` to `TODO(github-name): <link`
=> chore: change TODO format to refer to github name

.config/dictionaries/project.dic, .vscode/extensions.json, docs/Earthfile, docs/src/api/cat-gateway/rust.md
Fix docs by removing kroki diagrams.
Closes #296
=> fix: kroki ci errors

catalyst-gateway/Earthfile, catalyst-gateway/event-db/Earthfile, docs/Earthfile
=> feat: bump ci to 2.9.9

catalyst_voices/packages/catalyst_voices_shared/lib/src/responsive_builder/responsive_breakpoint_key.dart, catalyst_voices/packages/catalyst_voices_shared/lib/src/responsive_builder/responsive_builder.dart, catalyst_voices/packages/catalyst_voices_shared/test/src/responsive_builder_test.dart
The PR introduces a responsive generic widget builder to ensure the Catalyst Voices application's responsiveness across various devices. 
Closes #315 
This PR will unblock the work needed to updated and merge #324 and other responsive-related widgets.
=> feat: Add ResponsiveBuilder widget.

catalyst-gateway/Earthfile, catalyst-gateway/event-db/Earthfile, docs/Earthfile
=> feat: bump ci to 3.0.0

catalyst_voices/Earthfile, catalyst_voices/packages/catalyst_voices_assets/example/pubspec.yaml, catalyst_voices/packages/catalyst_voices_assets/pubspec.yaml, catalyst_voices/packages/catalyst_voices_blocs/pubspec.yaml, catalyst_voices/packages/catalyst_voices_localization/pubspec.yaml, catalyst_voices/packages/catalyst_voices_repositories/pubspec.yaml, catalyst_voices/packages/catalyst_voices_services/pubspec.yaml, catalyst_voices/packages/catalyst_voices_shared/pubspec.yaml, catalyst_voices/packages/catalyst_voices_view_models/pubspec.yaml, catalyst_voices/pubspec.yaml, catalyst_voices_packages/catalyst_analysis/example/pubspec.yaml, catalyst_voices_packages/catalyst_analysis/pubspec.yaml, melos.yaml, pubspec.yaml
=> chore: upgrade flutter to 3.19.5

catalyst_voices/packages/catalyst_voices_services/README.md
=> docs: update readme

catalyst-gateway/bin/src/follower.rs, catalyst-gateway/bin/src/registration/mod.rs
fixes syncing outage by removing panic path culprit
=> feat: hotfix slice indexing panic

catalyst-gateway/tests/api_tests/Earthfile
Fixed package-preprod-snapshot earthly version to `v2.11.1`
=> fix: Fix package-preprod-snapshot earthly version

.github/workflows/generate-allure-report.yml
Fixing issue with the test report target
> e.g., #1, #1
=> fix: rename test report target

catalyst-gateway/bin/src/cardano/cip36_registration/cip36_registration.cddl, catalyst-gateway/bin/src/cardano/cip36_registration/cip36_witness.cddl, catalyst-gateway/bin/src/cardano/cip36_registration/mod.rs, catalyst-gateway/bin/src/cardano/mod.rs, catalyst-gateway/bin/src/event_db/cardano/cip36_registration/mod.rs
Small refactoring of the cip36 parsing.
Provide a new struct, and new functions.
Improve `generate_from_tx_metadata` readability.
=> refactor: Small improving of the cip36 parsing

catalyst_voices/Earthfile, catalyst_voices/packages/catalyst_voices_services/lib/generated/catalyst_gateway/cat_gateway_api.models.swagger.g.dart
Updates catalyst_voices Earthfile to always copy source files from the root Earthfile's artifact to have a single source of truth.
#447
=> chore: update catalyst_voices earthly file to always take source files from artifact

catalyst-gateway/Cargo.lock, catalyst-gateway/Cargo.toml
Updating pallas version to reflect this changes which are not merged into the `main` branch of pallas.
- https://github.com/txpipe/pallas/pull/454
- https://github.com/txpipe/pallas/pull/426
part of https://github.com/input-output-hk/hermes/pull/231
=> feat: Bump pallas version

docs/src/architecture/10_quality/testplans/template.md
Updating the testplan url
> e.g., #1, #1
=> feat: Update-testplan-template

catalyst-gateway/Earthfile, catalyst-gateway/tests/api_tests/Earthfile
Try and prevent CI filling disk on our build machine.
=> fix(ci): Disable mithril cat-gateway tests that may be filling disk in CI

catalyst_voices/README.md
Adds common issues section related to flutter projects.
=> docs: add common issues docs

.markdownlint-cli2.jsonc, CHANGELOG.md, catalyst_voices_packages/catalyst_analysis/CHANGELOG.md, catalyst_voices_packages/catalyst_analysis/pubspec.yaml, catalyst_voices_packages/catalyst_cardano/catalyst_cardano/CHANGELOG.md, catalyst_voices_packages/catalyst_cardano/catalyst_cardano/pubspec.yaml, catalyst_voices_packages/catalyst_cardano/catalyst_cardano_platform_interface/CHANGELOG.md, catalyst_voices_packages/catalyst_cardano/catalyst_cardano_platform_interface/pubspec.yaml, catalyst_voices_packages/catalyst_cardano/catalyst_cardano_web/CHANGELOG.md, catalyst_voices_packages/catalyst_cardano/catalyst_cardano_web/pubspec.yaml, catalyst_voices_packages/catalyst_cardano_serialization/CHANGELOG.md, catalyst_voices_packages/catalyst_cardano_serialization/pubspec.yaml
Release dart/flutter packages to pub.dev. The changelogs are automatically generated by melos from commit history.
Packages will be published to pub.dev after this PR is merged.
=> chore(release): publish packages

Earthfile, catalyst-gateway/Cargo.toml, catalyst-gateway/Earthfile, catalyst-gateway/event-db/Earthfile, catalyst-gateway/tests/Earthfile, catalyst-gateway/tests/api_tests/Earthfile, catalyst_voices/Earthfile, catalyst_voices/uikit_example/Earthfile, docs/Earthfile
=> fix: update cat-ci to 3.1.15

.github/workflows/nightly-ci.yml
Fix nightly ci missing amazon environment
=> fix: add amz env to nightly

catalyst-gateway-crates/c509-certificate/src/c509_big_uint.rs, catalyst-gateway-crates/c509-certificate/src/c509_time.rs, catalyst-gateway-crates/c509-certificate/src/lib.rs
Implement encode and decode for type `Time` and `~biguint`
#608 
- Implement encode and decode for type `Time` and `~biguint` and provide test cases
=> feat: C509 Implement type `Time` and `~biguint`

Earthfile, catalyst-gateway-crates/c509-certificate/Earthfile, catalyst-gateway/Earthfile, catalyst-gateway/event-db/Earthfile, catalyst-gateway/tests/Earthfile, catalyst-gateway/tests/api_tests/Earthfile, catalyst_voices/Earthfile, catalyst_voices/uikit_example/Earthfile, docs/Earthfile
Update cat-ci version to 3.1.16
=> fix: update cat-ci to 3.1.16

Earthfile, catalyst-gateway-crates/c509-certificate/Earthfile, catalyst-gateway/Earthfile, catalyst-gateway/event-db/Earthfile, catalyst-gateway/tests/Earthfile, catalyst-gateway/tests/api_tests/Earthfile, catalyst_voices/Earthfile, catalyst_voices/uikit_example/Earthfile, docs/Earthfile
Update cat-ci version to v3.1.17
=> fix: Update cat-ci version to v3.1.17

catalyst_voices/Earthfile
=> fix: comment out publish

Earthfile, catalyst-gateway-crates/c509-certificate/Earthfile, catalyst-gateway/Earthfile, catalyst-gateway/event-db/Earthfile, catalyst-gateway/tests/Earthfile, catalyst-gateway/tests/api_tests/Earthfile, catalyst_voices/Earthfile, catalyst_voices/uikit_example/Earthfile, docs/Earthfile
=> chore: update ci to v3.1.18

catalyst_voices_packages/README.md
- Update README for Catalyst Voice pubs
=> chore: update README

Earthfile, catalyst-gateway-crates/c509-certificate/Earthfile, catalyst-gateway/Earthfile, catalyst-gateway/event-db/Earthfile, catalyst-gateway/tests/Earthfile, catalyst-gateway/tests/api_tests/Earthfile, catalyst_voices/Earthfile, catalyst_voices/uikit_example/Earthfile, docs/Earthfile
Update [catalyst-ci](https://github.com/input-output-hk/catalyst-ci) Earthfile imports to newest version
=> chore: update ci to v3.1.20

.github/workflows/generate-allure-report.yml, Earthfile, catalyst-gateway-crates/c509-certificate/Earthfile, catalyst-gateway/Earthfile, catalyst-gateway/event-db/Earthfile, catalyst-gateway/tests/Earthfile, catalyst-gateway/tests/api_tests/Earthfile, catalyst_voices/Earthfile, catalyst_voices/uikit_example/Earthfile, docs/Earthfile, melos.yaml
This PR fixes the coverage  for flutter/dart adding the reports for the flutter packages. Also it adds the coverage for the api tests. Coverage can be found here https://coveralls.io/github/input-output-hk/catalyst-voices
> e.g., #1, #1
=> fix: flutter coverage

.config/dictionaries/project.dic, catalyst_voices/lib/widgets/common/label_decorator.dart, catalyst_voices/lib/widgets/toggles/voices_checkbox.dart, catalyst_voices/lib/widgets/toggles/voices_checkbox_group.dart, catalyst_voices/lib/widgets/toggles/voices_radio.dart, catalyst_voices/lib/widgets/widgets.dart, catalyst_voices/packages/catalyst_voices_brands/lib/src/theme_extensions/voices_color_scheme.dart, catalyst_voices/packages/catalyst_voices_brands/lib/src/themes/catalyst.dart, catalyst_voices/packages/catalyst_voices_brands/lib/src/themes/widgets/toggles_theme.dart, catalyst_voices/pubspec.yaml, catalyst_voices/test/widgets/common/affix_decorator_test.dart, catalyst_voices/test/widgets/common/label_decorator_test.dart, catalyst_voices/test/widgets/toggles/voices_checkbox_group_test.dart, catalyst_voices/test/widgets/toggles/voices_checkbox_test.dart, catalyst_voices/uikit_example/lib/examples/voices_checkbox_example.dart, catalyst_voices/uikit_example/lib/examples/voices_radio_example.dart, catalyst_voices/uikit_example/lib/examples_list.dart
- Add `VoicesCheckbox` and `VoicesRadio` for Catalyst Voice frontend
https://github.com/user-attachments/assets/805d59c7-5331-4390-bbd1-eca59daeb7a5
Closes #652
=> feat: VoicesCheckbox, VoicesCheckboxGroup, VoicesRadio

catalyst_voices/lib/widgets/text_field/voices_text_field.dart
Actual:
TextField widget doesn't run validation if the text controller changes outside of the widget.
Expected:
TextField always validates itself.
=> fix: fixed text field validation if controller changed from the outside

catalyst_voices/uikit_example/lib/examples/voices_fab_example.dart, catalyst_voices/uikit_example/lib/examples_list.dart
Adds example for floating action buttons. The buttons were already styled correctly in previous PRs.
Closes #664
=> feat: floating action button

catalyst_voices/lib/widgets/indicators/voices_status_indicator.dart, catalyst_voices/lib/widgets/widgets.dart, catalyst_voices/uikit_example/lib/examples/voices_indicators_example.dart
- Add `VoicesStatusIndicator`
Closes #658
=> feat: VoicesStatusIndicator

catalyst_voices/uikit_example/lib/examples/voices_badge_example.dart, catalyst_voices/uikit_example/lib/examples_list.dart
Adds uikit badge examples
Closes #665
=> feat: uikit badge

catalyst_voices/packages/catalyst_voices_blocs/lib/src/catalyst_voices_blocs.dart, catalyst_voices/packages/catalyst_voices_blocs/lib/src/session/session_bloc.dart, catalyst_voices/packages/catalyst_voices_blocs/lib/src/session/session_event.dart, catalyst_voices/packages/catalyst_voices_blocs/lib/src/session/session_state.dart, catalyst_voices/packages/catalyst_voices_blocs/lib/src/user_profile/user_profile.dart, catalyst_voices/packages/catalyst_voices_blocs/lib/src/user_profile/user_profile_bloc.dart, catalyst_voices/packages/catalyst_voices_blocs/lib/src/user_profile/user_profile_event.dart, catalyst_voices/packages/catalyst_voices_blocs/lib/src/user_profile/user_profile_state.dart, catalyst_voices/packages/catalyst_voices_models/lib/src/catalyst_voices_models.dart, catalyst_voices/packages/catalyst_voices_models/lib/src/user/user.dart, catalyst_voices/uikit_example/lib/examples/voices_spaces_example.dart, catalyst_voices/uikit_example/lib/main.dart, catalyst_voices/uikit_example/lib/widgets/session_header.dart, catalyst_voices/uikit_example/lib/widgets/user_header.dart
Adds dummy user profile management
=> feat: add user profile bloc

catalyst_voices/integration_test/main.dart, catalyst_voices/lib/widgets/rich_text/voices_rich_text.dart, catalyst_voices/test_driver/Earthfile
- fix a few dart warnings
- fix formatting to align with project recommendations
=> fix(cat-voices-fronted): dart warnings

catalyst_voices/web/index.html
- add flutter_inappwebview_web as dependency to index.html to fix web target
=> fix(frontend): add flutter_inappwebview_web to fix web target

catalyst_voices/lib/pages/funded_projects/funded_projects_page.dart, catalyst_voices/lib/pages/voting/voting_page.dart, catalyst_voices/lib/widgets/cards/funded_proposal_card.dart, catalyst_voices/packages/catalyst_voices_brands/lib/src/themes/catalyst.dart, catalyst_voices/packages/catalyst_voices_localization/lib/generated/catalyst_voices_localizations.dart, catalyst_voices/packages/catalyst_voices_localization/lib/generated/catalyst_voices_localizations_en.dart, catalyst_voices/packages/catalyst_voices_localization/lib/generated/catalyst_voices_localizations_es.dart, catalyst_voices/packages/catalyst_voices_localization/lib/l10n/intl_en.arb
Adds funded projects space
Closes #739
=> feat: funded projects space

catalyst_voices/lib/pages/workspace/workspace_page.dart, catalyst_voices/lib/widgets/rich_text/voices_rich_text.dart
Simplify MVE1 workspace
Closes #872
=> feat(cat-voices): Simplify MVE1 workspace

.github/workflows/ci.yml
=> ci(general): locks version and updates events

catalyst_voices_packages/catalyst_cardano/catalyst_cardano/wallet-automation/Earthfile
This PR is making use of Playwright function from Earthfile in catalyst-ci
https://github.com/input-output-hk/catalyst-ci/pull/317
Replaced part of the code with function call in Playwright Earthfile
No breaking changes
https://github.com/input-output-hk/catalyst-ci/pull/317
=> chore(flutter/catalyst_cardano): add playwright function to Earthfile

catalyst_voices/lib/pages/registration/create_keychain/create_keychain_panel.dart, catalyst_voices/lib/pages/registration/placeholder_panel.dart, catalyst_voices/lib/pages/registration/registration_dialog.dart, catalyst_voices/lib/pages/registration/registration_info_panel.dart, catalyst_voices/lib/pages/registration/wallet_link/stage/roles_chooser_panel.dart, catalyst_voices/lib/pages/registration/wallet_link/stage/roles_summary_panel.dart, catalyst_voices/packages/catalyst_voices_blocs/lib/src/registration/registration_cubit.dart, catalyst_voices/packages/catalyst_voices_models/lib/src/registration/create_keychain_stage.dart, catalyst_voices/packages/catalyst_voices_models/lib/src/registration/registration_step.dart
Adds placeholders with next/back button to not yet implemented steps in registration.
Refers #818
=> feat(cat-voices): registration flow placeholders

catalyst_voices/lib/pages/registration/create_keychain/stage/check_seed_phrase_instructions_panel.dart, catalyst_voices/lib/pages/registration/create_keychain/stage/instructions_panel.dart, catalyst_voices/lib/pages/registration/create_keychain/stage/seed_phrase_check_panel.dart, catalyst_voices/lib/pages/registration/create_keychain/stage/seed_phrase_check_result_panel.dart, catalyst_voices/lib/pages/registration/create_keychain/stage/seed_phrase_panel.dart, catalyst_voices/lib/pages/registration/create_keychain/stage/splash_panel.dart, catalyst_voices/lib/pages/registration/get_started/get_started_panel.dart, catalyst_voices/lib/pages/registration/placeholder_panel.dart, catalyst_voices/lib/pages/registration/registration_stage_message.dart, catalyst_voices/lib/pages/registration/registration_stage_navigation.dart, catalyst_voices/lib/pages/registration/wallet_link/stage/intro_panel.dart, catalyst_voices/lib/pages/registration/wallet_link/stage/select_wallet_panel.dart, catalyst_voices/lib/pages/registration/wallet_link/stage/wallet_details_panel.dart, catalyst_voices/lib/widgets/common/delayed_widget.dart, catalyst_voices/lib/widgets/common/infrastructure/voices_loadable.dart, catalyst_voices/lib/widgets/widgets.dart, catalyst_voices/packages/catalyst_voices_models/pubspec.yaml
Extracting more common widgets into separate widgets for better clarity.
=> feat(cat-voices): registration components

catalyst_voices/lib/pages/registration/finish_account/finish_account_creation_panel.dart, catalyst_voices/lib/pages/registration/registration_dialog.dart, catalyst_voices/lib/pages/registration/registration_info_panel.dart, catalyst_voices/lib/pages/registration/registration_progress.dart, catalyst_voices/packages/catalyst_voices_blocs/lib/src/registration/registration_cubit.dart, catalyst_voices/packages/catalyst_voices_localization/lib/generated/catalyst_voices_localizations.dart, catalyst_voices/packages/catalyst_voices_localization/lib/generated/catalyst_voices_localizations_en.dart, catalyst_voices/packages/catalyst_voices_localization/lib/generated/catalyst_voices_localizations_es.dart, catalyst_voices/packages/catalyst_voices_localization/lib/l10n/intl_en.arb
Adds finish account creation panel
Part of #816
=> feat(cat-voices): finish account creation panel

catalyst_voices/lib/pages/registration/finish_account/finish_account_creation_panel.dart
Fixes static analysis (wrongly formatted code).
=> fix(cat-voices): reformat code

.github/workflows/ci.yml
=> ci(general): locks forge cli to v0.2.0

.github/workflows/ci.yml, blueprint.cue, catalyst_voices/blueprint.cue
=> ci(cat-voices): adds deployment configuration

catalyst-gateway/Earthfile
This just adds a publish target for cat-gateway service.
=> chore(cat-gateway): Add publish CI target for cat-gateway

catalyst-gateway/bin/Cargo.toml
Updates `cardano-chain-follower` crate to `v0.0.4`.
=> fix(cat-gateway): Bump cardano-chain-follower to v0.0.4

catalyst_voices/lib/app/view/app_session_listener.dart, catalyst_voices/lib/pages/spaces/spaces_shell_page.dart, catalyst_voices/lib/routes/routing/routes.dart, catalyst_voices/lib/widgets/app_bar/session/session_action_header.dart, catalyst_voices/lib/widgets/app_bar/session/session_state_header.dart, catalyst_voices/packages/catalyst_voices_assets/lib/generated/assets.gen.dart
Limit scope of the app only to MVE1
=> fix: limit scope for mve1

.github/workflows/ci.yml, .github/workflows/generate-allure-report.yml, blueprint.cue, catalyst-gateway/Earthfile, catalyst-gateway/blueprint.cue, catalyst_voices/Earthfile, catalyst_voices/blueprint.cue
=> ci(general): updates to v1.2.1 and forge v0.4.0

catalyst_voices/lib/widgets/containers/space_side_panel.dart
Implement toggling side panels.
Closes #838 
https://github.com/user-attachments/assets/28361db2-395b-4024-8286-92a7aa248850
=> feat: Workspace - L/R Panels open close

.github/workflows/ci.yml, .github/workflows/generate-allure-report.yml
=> ci(general): updates forge to v0.5.0

.github/workflows/ci.yml, .github/workflows/generate-allure-report.yml
=> ci(general): bumps CI to v1.2.2

.config/dictionaries/project.dic, Earthfile, catalyst-gateway/Earthfile, catalyst-gateway/event-db/Earthfile, catalyst-gateway/tests/Earthfile, catalyst-gateway/tests/api_tests/Earthfile, catalyst_voices/Earthfile, catalyst_voices/uikit_example/Earthfile, catalyst_voices_packages/catalyst_cardano/catalyst_cardano/wallet-automation/Earthfile, docs/Earthfile, justfile, utilities/docs-preview/.gitignore, utilities/docs-preview/Earthfile, utilities/docs-preview/justfile
Target to easy preview docs locally.
=> docs(docs): Add targets to make it easy to locally preview docs.

catalyst_voices/apps/voices/lib/pages/registration/wallet_link/stage/roles_summary_panel.dart, catalyst_voices/packages/internal/catalyst_voices_localization/lib/generated/catalyst_voices_localizations.dart, catalyst_voices/packages/internal/catalyst_voices_localization/lib/generated/catalyst_voices_localizations_en.dart, catalyst_voices/packages/internal/catalyst_voices_localization/lib/generated/catalyst_voices_localizations_es.dart, catalyst_voices/packages/internal/catalyst_voices_localization/lib/l10n/intl_en.arb
Review my role registration transaction before signing, so that I have confidence in what I'm submitting to chain.
Resolves #1088 
Deleting unused translation, adding translation "Review registration transaction". Changing text in button in roles summary panel
=> refactor(cat-voices): Update button text in roles_summary_panel

catalyst_voices/apps/voices/lib/pages/registration/recover/seed_phrase/unlock_password_panel.dart, catalyst_voices/packages/internal/catalyst_voices_blocs/lib/src/registration/cubits/recover_cubit.dart, catalyst_voices/packages/internal/catalyst_voices_services/lib/src/registration/registration_service.dart
Recovered account keychain was create with wrong unlock password
=> fix(cat-voices): account recovery keychain password

catalyst_voices/apps/voices/lib/widgets/common/animated_expand_chevron.dart
Fixes wrong expand arrow rotation value
=> fix(cat-voices): expand arrow rotation

.github/workflows/generate-allure-report.yml, catalyst_voices/Earthfile, catalyst_voices/apps/voices/lib/pages/workspace/workspace_guidance_view.dart, catalyst_voices/melos.yaml
Fixes code coverage and junit reports, before this PR the artifacts for the report files were not generated correctly.
=> fix(cat-voices): code coverage and test reports

.github/ISSUE_TEMPLATE/test_plan.yml
Updates testplan template 
> e.g., #1, #1
=> feat: Update testplan template

catalyst_voices/apps/voices/lib/common/formatters/date_formatter.dart, catalyst_voices/apps/voices/lib/widgets/modals/campaign/campaign_details_tile.dart, catalyst_voices/apps/voices/lib/widgets/tiles/voices_expansion_tile.dart, catalyst_voices/apps/voices/lib/widgets/widgets.dart, catalyst_voices/apps/voices/test/common/formatters/date_formatter_test.dart, catalyst_voices/packages/internal/catalyst_voices_localization/lib/l10n/intl_en.arb
- Adds generic `VoicesExpansionTile` which uses material `ExpansionTile`
- Adds specialised `CampaignDetailsTile`
Resolves #1184 
https://github.com/user-attachments/assets/a8b09517-7f5c-444c-b35d-3f7e0dcffe4b
=> feat(cat-voices): campaign details and information

catalyst_voices/apps/voices/lib/pages/account/unlock_keychain_dialog.dart, catalyst_voices/apps/voices/lib/widgets/text_field/voices_password_text_field.dart, catalyst_voices/apps/voices/lib/widgets/text_field/voices_text_field.dart
Adds autofocus for password field in unlock keychain dialog for faster input.
=> feat(cat-voices): autofocus password field to enable faster input

docs/src/architecture/08_concepts/key-derivation/.pages, docs/src/architecture/08_concepts/key-derivation/derivation.md
ED25519 key Derivation path specification.
Closes #1299
=> feat(docs): Document the key derivation path for Project Catalyst ED25519 Keys

catalyst_voices/README.md, catalyst_voices/justfile
New just functions for code setup for build.
=> feat(cat-voices): additional just functions for faster startup

.github/workflows/ci.yml, .github/workflows/generate-allure-report.yml, blueprint.cue
=> chore: updates forge -> 0.7.0 and CI -> 1.4.0

.github/workflows/ci.yml, .github/workflows/generate-allure-report.yml, catalyst_voices/blueprint.cue
=> chore: updates forge -> 0.8.0 and CI -> 1.5.0

catalyst-gateway/bin/Cargo.toml, catalyst-gateway/bin/src/db/index/block/rbac509/insert_rbac509.rs, catalyst-gateway/bin/src/db/index/block/rbac509/mod.rs
=> fix(cat-gateway): Update `CIP509` new implementation

catalyst-gateway/bin/src/service/utilities/middleware/schema_validation.rs
- Log schema validation check error.
Without logging this error it was hard (for me) to understand why the responses returned the 503 error. Now the reason for error is clear. In my case I haven't started event-db, so the requests that needed to connect to it timed out.
=> fix(cat-voices): Log schema version check error

catalyst_voices/apps/voices/integration_test/app_test.dart, catalyst_voices/apps/voices/lib/configs/bootstrap.dart
This PR adds optional `router` parameter to the bootstrap function for easier nav direction testing
=> feat(cat-voices): bootstrap router parameter

catalyst_voices/apps/voices/lib/configs/bootstrap.dart, catalyst_voices/apps/voices/lib/dependency/dependencies.dart
Expose `restartDependencies` / `registerDependencies` so tests can restart app before/after tests
=> feat(cat-voices): expose restart dependencies method

catalyst_voices/apps/voices/integration_test/pageobject/onboarding_page.dart, catalyst_voices/apps/voices/integration_test/utils/translations_utils.dart, catalyst_voices/apps/voices/lib/pages/registration/widgets/information_panel.dart
=> test(cat-voices): formatting fix

.config/dictionaries/project.dic, .github/CODEOWNERS
=> chore(general): update codeowners

catalyst-gateway/tests/schemathesis_tests/Earthfile
=> fix(cat-gateway): schemathesis test

.github/workflows/ci.yml, .github/workflows/generate-allure-report.yml, blueprint.cue, catalyst_voices/blueprint.cue
=> ci(general): upgrades CI to v1.7.0 and forge to v0.10.0

.github/workflows/flutter-uikit-example-firebase-deploy.yml
=> ci(general): fixes flutter uitkit workflow

catalyst-gateway/Justfile
This PR adds the internal api key env var that was missing in the just example
> e.g., #1, #1
=> fix(cat-gateway): adds missing example apikey for cat-gateway

catalyst-gateway/bin/src/service/common/auth/rbac/scheme.rs
=> feat(cat-gateway): rbac switch for testing

.github/workflows/ci.yml, .github/workflows/flutter-uikit-example-firebase-deploy.yml, .github/workflows/generate-allure-report.yml, .github/workflows/nightly-ci.yml
=> chore(general): updates forge CLI to v0.11.0 and CI to v1.7.1

.config/dictionaries/project.dic, catalyst-gateway/Earthfile, catalyst-gateway/bin/src/db/index/schema/cql/namespace.cql, catalyst-gateway/bin/src/db/index/schema/mod.rs, catalyst-gateway/bin/src/service/api/health/live_get.rs, catalyst-gateway/bin/src/service/api/health/mod.rs, catalyst-gateway/bin/src/settings/cassandra_db.rs, catalyst-gateway/blueprint.cue, catalyst-gateway/entrypoint.sh, catalyst-gateway/event-db/Earthfile, catalyst-gateway/event-db/blueprint.cue, catalyst-gateway/event-db/setup-db.sql
=> chore(cat-gateway): adds deployment

catalyst-gateway/bin/src/db/index/block/cip36/insert_cip36.rs, catalyst-gateway/bin/src/db/index/block/cip36/insert_cip36_for_vote_key.rs, catalyst-gateway/bin/src/db/index/block/cip36/insert_cip36_invalid.rs, catalyst-gateway/bin/src/db/index/block/cip36/mod.rs
Fix CIP36 indexing
Related to https://github.com/input-output-hk/catalyst-voices/issues/1759.
=> fix(cat-gateway): CIP36 indexing

catalyst-gateway/blueprint.cue, catalyst-gateway/event-db/blueprint.cue
=> chore(cat-gateway): disables automatic deployments for cat-gateway

catalyst_voices/apps/voices/integration_test/Earthfile
=> test(cat-voices): Enable failing integration tests quick fix

catalyst-gateway/tests/schemathesis_tests/Earthfile
Fixes schemathesis target
> e.g., #1, #1
=> fix(cat-gateway): nightly schemathesis

Earthfile, catalyst-gateway/Earthfile, catalyst-gateway/event-db/Earthfile, catalyst-gateway/tests/Earthfile, catalyst-gateway/tests/api_tests/Earthfile, catalyst_voices/Earthfile, catalyst_voices/packages/libs/catalyst_cardano/catalyst_cardano/wallet-automation/Earthfile, catalyst_voices/packages/libs/catalyst_key_derivation/Earthfile, catalyst_voices/packages/libs/catalyst_key_derivation/rust/Earthfile, catalyst_voices/utilities/uikit_example/Earthfile, docs/Earthfile, utilities/docs-preview/Earthfile
Bump ci version to `v3.2.38`
- #1808 have to be merged first
- Unblocks #1789
=> chore: bump ci ver

catalyst-gateway/bin/src/db/event/signed_docs/full_signed_doc.rs
Reverts input-output-hk/catalyst-voices#1833
=> Revert "fix(signed-doc): full signed doc store"

catalyst-gateway/bin/src/service/api/documents/mod.rs, catalyst-gateway/tests/api_tests/api_tests/test_signed_doc.py, catalyst-gateway/tests/schemathesis_tests/Earthfile
Made a Catalyst Signed Document endpoints from `draft` to `v1`.
=> feat(cat-gateway): Catalyst Signed Document endpoints v1

catalyst_voices/apps/voices/lib/pages/proposal_builder/proposal_builder_page.dart, catalyst_voices/apps/voices/lib/widgets/buttons/voices_buttons.dart, catalyst_voices/apps/voices/lib/widgets/rich_text/voices_rich_text.dart, catalyst_voices/apps/voices/lib/widgets/snackbar/voices_snackbar.dart, catalyst_voices/apps/voices/lib/widgets/snackbar/voices_snackbar_action.dart, catalyst_voices/apps/voices/lib/widgets/snackbar/voices_snackbar_type.dart, catalyst_voices/apps/voices/lib/widgets/text_field/voices_text_field.dart, catalyst_voices/apps/voices/lib/widgets/tiles/editable_tile.dart, catalyst_voices/packages/internal/catalyst_voices_blocs/lib/src/proposal_builder/proposal_builder_bloc.dart, catalyst_voices/packages/internal/catalyst_voices_brands/lib/src/utils/typedefs.dart, catalyst_voices/packages/internal/catalyst_voices_localization/lib/l10n/intl_en.arb, catalyst_voices/packages/internal/catalyst_voices_models/lib/src/document/document.dart, catalyst_voices/packages/internal/catalyst_voices_shared/lib/src/utils/debouncer.dart, catalyst_voices/packages/internal/catalyst_voices_view_models/lib/src/catalyst_voices_view_models.dart, catalyst_voices/packages/internal/catalyst_voices_view_models/lib/src/proposal_builder/exception/proposal_builder_exception.dart, catalyst_voices/utilities/uikit_example/lib/examples/voices_snackbar_example.dart
- Add snackbar with validation issues to proposal editor.
- Fix snackbar colors.
- Make the validation errors in proposal editor more visible.
Refers #1659
=> feat(cat-voices): proposal editor validation snackbar

.vscode/launch.recommended.json
Update on launch.recommeded.json
Resolves #1872 
#1867 - I want to give instructions for specific launch configurations to be used
=> chore(cat-voices): update launch.recommended.json

.github/workflows/ci.yml, .github/workflows/flutter-uikit-example-firebase-deploy.yml, .github/workflows/generate-allure-report.yml, .github/workflows/nightly-ci.yml, catalyst-gateway/blueprint.cue, catalyst_voices/blueprint.cue
=> ci(general): bumps forge to v0.14.0

catalyst-gateway/bin/src/utils/blake2b_hash.rs
Removed unused `blake2b` hash functions
=> fix(cat-gateway): Remove unused `blake2b` hash functions

catalyst-gateway/bin/src/service/common/responses/code_412_precondition_failed.rs, catalyst-gateway/bin/src/service/common/types/generic/error_msg.rs
Update `ContentErrorDetail` and `ErrorMessage` OpenApi definitions, to fix schemathesis failure.
```
./c/t/schemathesis_tests+test-ci-schemathesis | _________________________ POST /api/v1/document/index __________________________
./c/t/schemathesis_tests+test-ci-schemathesis | 1. Test Case ID: rx5Xtc
./c/t/schemathesis_tests+test-ci-schemathesis | 
./c/t/schemathesis_tests+test-ci-schemathesis | - Response violates schema
./c/t/schemathesis_tests+test-ci-schemathesis | 
./c/t/schemathesis_tests+test-ci-schemathesis |     'parse request payload error: Expected input type "DocumentIndexQueryFilter", found [null,[null,null,[]],{"\U000b89fe3Q\\u0016ÕTÉ\U000f4ed3\U000b7376+h¡\x8d𥹅\U0009322e":{"Ç":null,"ÿ-\x8d":[null,null],"祿\U00058956\x90\\u0018tV\U0009500f\U00101ca7\\u0005":{"g\x82즊\\tü\\u001c …
```
=> fix(cat-gateway): Update `ContentErrorDetail` and `ErrorMessage` OpenApi definitions.

catalyst_voices/apps/voices/lib/dependency/dependencies.dart, catalyst_voices/apps/voices/lib/pages/overall_spaces/space/discovery_overview.dart, catalyst_voices/apps/voices/lib/pages/overall_spaces/space/workspace_overview.dart, catalyst_voices/packages/internal/catalyst_voices_blocs/lib/src/proposal_builder/proposal_builder_bloc.dart, catalyst_voices/packages/internal/catalyst_voices_blocs/lib/src/proposal_builder/proposal_builder_state.dart, catalyst_voices/packages/internal/catalyst_voices_blocs/lib/src/registration/cubits/recover_cubit.dart, catalyst_voices/packages/internal/catalyst_voices_blocs/lib/src/registration/registration_cubit.dart, catalyst_voices/packages/internal/catalyst_voices_blocs/test/proposals/proposals_cubit_test.dart, catalyst_voices/packages/internal/catalyst_voices_models/lib/src/crypto/catalyst_key_pair.dart, catalyst_voices/packages/internal/catalyst_voices_models/lib/src/crypto/catalyst_private_key.dart, catalyst_voices/packages/internal/catalyst_voices_models/lib/src/document/data/document_data_metadata.dart, catalyst_voices/packages/internal/catalyst_voices_models/lib/src/proposal/proposal.dart, catalyst_voices/packages/internal/catalyst_voices_models/lib/src/proposal/proposal_data.dart, catalyst_voices/packages/internal/catalyst_voices_models/lib/src/proposal/proposal_enums.dart, catalyst_voices/packages/internal/catalyst_voices_models/test/proposal/proposal_pagination_items_test.dart, catalyst_voices/packages/internal/catalyst_voices_repositories/lib/src/document/document_repository.dart, catalyst_voices/packages/internal/catalyst_voices_repositories/lib/src/document/source/document_data_remote_source.dart, catalyst_voices/packages/internal/catalyst_voices_repositories/lib/src/dto/document/document_data_dto.dart, catalyst_voices/packages/internal/catalyst_voices_repositories/lib/src/dto/proposal/proposal_submission_action_dto.dart, catalyst_voices/packages/internal/catalyst_voices_repositories/lib/src/proposal/proposal_repository.dart, catalyst_voices/packages/internal/catalyst_voices_services/lib/src/auth/auth_service.dart, catalyst_voices/packages/internal/catalyst_voices_services/lib/src/proposal/proposal_service.dart, catalyst_voices/packages/internal/catalyst_voices_services/lib/src/registration/registration_service.dart, catalyst_voices/packages/internal/catalyst_voices_services/lib/src/registration/registration_transaction_builder.dart, catalyst_voices/packages/internal/catalyst_voices_services/test/src/auth/auth_service_test.dart, catalyst_voices/packages/internal/catalyst_voices_services/test/src/proposal/proposal_service_test.dart, catalyst_voices/packages/libs/catalyst_key_derivation/lib/src/bip32_ed25519/bip32_ed25519_private_key.dart
Publish signed documents with [proposal submission actions.](https://github.com/input-output-hk/catalyst-libs/pull/208/files#diff-af129a1068b93ba2b804f705d49c35c209347441ae8f9619a4ec4e78edb9f9bb)
TODO:
- after publishing signed document remove the local draft
- update the proposal builder state with new proposal status
- consider to put newly signed document into documents cache
Refers #1704
=> feat(cat-voices): publish proposal actions - part 1

catalyst_voices/packages/internal/catalyst_voices_assets/assets/document_templates/proposal/F14-Generic/0ce8ab38-9258-4fbc-a62e-7faa6e58318f.schema.json, catalyst_voices/packages/internal/catalyst_voices_assets/assets/document_templates/proposal/F14-Generic/example.proposal.json, catalyst_voices/packages/internal/catalyst_voices_repositories/lib/src/dto/document/document_dto.dart
Updates the proposal template to latest available at proposal.schema.json
Refers #1947
=> feat(cat-voices): update proposal template to latest

catalyst-gateway/bin/src/logger.rs, catalyst-gateway/tests/schemathesis_tests/Earthfile
=> fix(cat-gateway): Fixing clippy issues for cat-gateway

catalyst_voices/apps/voices/lib/pages/discovery/sections/campaign_categories.dart, catalyst_voices/apps/voices/lib/pages/discovery/sections/most_recent_proposals.dart, catalyst_voices/apps/voices/lib/widgets/heroes/section_hero.dart, catalyst_voices/packages/internal/catalyst_voices_repositories/lib/src/document/document_repository.dart, catalyst_voices/packages/internal/catalyst_voices_repositories/lib/src/proposal/proposal_repository.dart
A few changes to discovery page to better handle UI on ultra wide screen
N/A
- hero section better handle height of the video
- campaign category center horizontally
- finding bug not passed unique arguments in proposal_repository
N/A
N/A
=> chore(cat-voices): wide screen improvments in discovery page

catalyst-gateway/bin/src/service/api/cardano/staking/assets_get.rs
Fix bug when asset value is outside of valid range.
Closes #2047
=> fix(cat-gateway): Debug staked asset value check

catalyst-gateway/bin/Cargo.toml, catalyst-gateway/bin/src/service/common/auth/rbac/scheme.rs
Bumped cat-libs version to bring a fix for the `cardano-chain-follower` https://github.com/input-output-hk/catalyst-libs/pull/258
=> fix(cat-gateway): Bump cat-libs version with the fixed cardano-chain-follower

catalyst-gateway/tests/api_tests/integration/test_signed_doc.py, catalyst-gateway/tests/api_tests/test_data/signed_docs/submission_action.json
Add tests for submission action.
=> feat(cat-voices): submission action tests

.github/workflows/ci.yml, .github/workflows/flutter-uikit-example-firebase-deploy.yml, .github/workflows/generate-allure-report.yml, .github/workflows/nightly-ci.yml, catalyst-gateway/blueprint.cue, catalyst_voices/blueprint.cue
=> ci(general): bumps forge to v0.16.0

catalyst-gateway/blueprint.cue, catalyst_voices/Earthfile, catalyst_voices/blueprint.cue
=> ci(general): updates gateway/voices deployments

catalyst-gateway/blueprint.cue
=> ci(general): uses GIT_HASH_OR_TAG with gateway deployment

Earthfile, catalyst-gateway/Earthfile, catalyst-gateway/event-db/Earthfile, catalyst-gateway/tests/Earthfile, catalyst-gateway/tests/api_tests/Earthfile, catalyst_voices/Earthfile, catalyst_voices/packages/libs/catalyst_cardano/catalyst_cardano/wallet-automation/Earthfile, catalyst_voices/packages/libs/catalyst_key_derivation/Earthfile, catalyst_voices/packages/libs/catalyst_key_derivation/pubspec.yaml, catalyst_voices/packages/libs/catalyst_key_derivation/rust/Cargo.toml, catalyst_voices/packages/libs/catalyst_key_derivation/rust/Earthfile, catalyst_voices/utilities/uikit_example/Earthfile, docs/Earthfile, utilities/docs-preview/Earthfile
Revert bumping `flutter_rust_bridge` from `2.9.0` to `2.5.1`
=> fix(cat-gateway): Downgrade `flutter_rust_bridge` to `2.5.1`

catalyst-gateway/bin/src/service/api/cardano/rbac/mod.rs, catalyst-gateway/bin/src/service/api/cardano/rbac/registrations_get/mod.rs, catalyst-gateway/bin/src/service/api/documents/mod.rs, catalyst-gateway/bin/src/service/common/auth/none_or_rbac.rs, catalyst-gateway/bin/src/service/common/auth/rbac/scheme.rs, catalyst-gateway/bin/src/service/common/auth/rbac/token.rs
After merging RBAC endpoint code, it broken some parts related to the RBAC auth token
=> fix(cat-gateway): RBAC token compilation fixes

catalyst_voices/packages/internal/catalyst_voices_localization/lib/l10n/intl_en.arb, catalyst_voices/packages/internal/catalyst_voices_view_models/lib/src/document/validation/localized_document_validation_result.dart
Better validation error for checkbox in proposal builder.
Closes #2248
=> fix(cat-voices): better validation error for checkbox in proposal builder

catalyst_voices/apps/voices/integration_test/pageobject/onboarding/create_flow/step_3_setup_base_profile.dart, catalyst_voices/apps/voices/lib/pages/registration/create_base_profile/stage/setup_panel.dart, catalyst_voices/packages/internal/catalyst_voices_localization/lib/l10n/intl_en.arb
Change text about ideascale account to version that is more clear for users.
Closes #2186
N/A
N/A
N/A
N/A
=> chore(cat-voices): change localize text about ideascale account to more clear one

catalyst_voices/apps/voices/lib/pages/proposal/widget/proposal_share_button.dart, catalyst_voices/packages/internal/catalyst_voices_blocs/lib/src/proposal/proposal_cubit.dart, catalyst_voices/packages/internal/catalyst_voices_localization/lib/l10n/intl_en.arb, catalyst_voices/packages/internal/catalyst_voices_view_models/lib/src/proposal/proposal_view_header.dart
This pr adds share funtionality inside proposal view
Closes #2208
looking at favorite button I implemented the same funtionality for share button
N/A
N/A
N/A
=> feat(cat-voices): share dialog in proposal view

catalyst_voices/apps/voices/lib/pages/proposal_builder/proposal_builder_navigation_panel.dart, catalyst_voices/apps/voices/lib/pages/proposal_builder/proposal_builder_page.dart, catalyst_voices/apps/voices/lib/pages/proposal_builder/proposal_builder_setup_panel.dart, catalyst_voices/apps/voices/lib/pages/treasury/treasury_details_panel.dart, catalyst_voices/apps/voices/lib/pages/treasury/treasury_navigation_panel.dart, catalyst_voices/apps/voices/lib/pages/workspace/page/workspace_page.dart, catalyst_voices/apps/voices/lib/widgets/containers/sidebar/space_side_panel.dart, catalyst_voices/packages/internal/catalyst_voices_models/lib/src/campaign/campaign_timeline.dart
Change icons and remove text in header section of sidebar navigation in proposal builder to match new design. 
Also small fix to warning dialog about closing submission date. 
Closes #2210
N/A
N/A
N./A
N/A
=> chore(cat-voices): Update icons in sidebar of proposal builder

catalyst-gateway/bin/src/db/event/mod.rs, catalyst-gateway/bin/src/settings/event_db.rs, catalyst-gateway/bin/src/settings/mod.rs, catalyst-gateway/blueprint.cue
[dynamic postgres config](https://docs.rs/bb8/latest/bb8/struct.Builder.html)
=> feat(cat-gateway): dynamic postgres config

catalyst-gateway/blueprint.cue
=> fix(cat-gateway):  aws vault kv

catalyst-gateway/tests/api_tests/Earthfile, catalyst-gateway/tests/api_tests/api/v1/document.py, catalyst-gateway/tests/api_tests/integration/test_assets.py, catalyst-gateway/tests/api_tests/integration/test_signed_doc.py, catalyst-gateway/tests/schemathesis_tests/Earthfile
- Fixing `test_assets.py`
- Fixing `test_signed_doc.py`
=> fix(cat-gateway): Fix test_assets.py

catalyst_voices/apps/voices/lib/pages/workspace/user_proposals/user_proposal_section.dart, catalyst_voices/apps/voices/lib/pages/workspace/user_proposals/user_proposals.dart, catalyst_voices/apps/voices/lib/widgets/headers/section_learn_more_header.dart, catalyst_voices/packages/internal/catalyst_voices_localization/lib/l10n/intl_en.arb
This pr changes normal list of proposal in workspace to collapseable ones
#2286 
-adding collapseable feature
N/A
N/A
N/A
=> feat(cat-voices): adding collapseable feature to list of user proposal

catalyst_voices/packages/internal/catalyst_voices_localization/lib/l10n/intl_en.arb
Remove phrases needed info from add roles modal.
> e.g., #1, #1
=> chore(cat-voices): Add role info, remove phrases text

catalyst-gateway/bin/Cargo.toml
Fixing failing `cat-gateway` CI build https://github.com/input-output-hk/catalyst-libs/pull/295
=> fix(cat-gateway): Fix CI

Earthfile, catalyst-gateway/Earthfile, catalyst-gateway/deny.toml, catalyst-gateway/event-db/Earthfile, catalyst-gateway/tests/Earthfile, catalyst-gateway/tests/api_tests/Earthfile, catalyst_voices/Earthfile, catalyst_voices/packages/libs/catalyst_cardano/catalyst_cardano/wallet-automation/Earthfile, catalyst_voices/packages/libs/catalyst_key_derivation/Earthfile, catalyst_voices/packages/libs/catalyst_key_derivation/rust/Earthfile, catalyst_voices/packages/libs/catalyst_key_derivation/rust/deny.toml, catalyst_voices/utilities/uikit_example/Earthfile, docs/Earthfile, utilities/docs-preview/Earthfile
- Bumping `catalyst-ci` version, updating `deny.toml` files
=> feat(general): Bump `catalyst-ci` version

catalyst-gateway/tests/api_tests/integration/__init__.py, catalyst-gateway/tests/api_tests/utils/rbac_chain.py
Fixing catalyst-id generation inside the integration tests
=> fix(cat-gateway): Fix cat-id generation for the signed docs tests

catalyst_voices/apps/voices/lib/widgets/modals/comment/submit_comment_error_dialog.dart, catalyst_voices/apps/voices/lib/widgets/modals/voices_desktop_dialog.dart, catalyst_voices/apps/voices/lib/widgets/modals/voices_info_dialog.dart
Fixes comment failed dialog size
**Before**
**After**
=> fix(cat-voices): comment failed dialog spacing

catalyst_voices/apps/voices/lib/widgets/cards/category_proposals_details_card.dart
Simple fix to offstage button if proposals count is 0 
#2411 
- offstage button 
N/A
N/A
=> feat(cat-voices): offstage viewProposals button if count is 0

catalyst-gateway/bin/Cargo.toml, catalyst-gateway/bin/src/service/api/documents/common/mod.rs, catalyst-gateway/tests/api_tests/test_data/signed_docs/submission_action.json
Bumping catalyst-libs dependencies, to bring the following important updates:
- https://github.com/input-output-hk/catalyst-libs/pull/298
- https://github.com/input-output-hk/catalyst-libs/pull/297
Fixed integration test for the proposal submission action document test cases
=> feat(cat-gateway): Bump cat-libs version

catalyst_voices/apps/voices/lib/pages/account/unlock_keychain_dialog.dart, catalyst_voices/packages/internal/catalyst_voices_localization/lib/l10n/intl_en.arb
=> chore: update recover account wording

catalyst_voices/apps/voices/lib/widgets/cards/proposal/pending_proposal_card.dart, catalyst_voices/apps/voices/lib/widgets/modals/voices_share_dialog.dart
Use full base uri when sharing url + fix location path 
Instead of sharing `voices.dev.projectcatalyst.io/discovery` to `https://voices.dev.projectcatalyst.io/discovery`
=> fix(cat-voices): share proposal local and add https in link

catalyst-gateway/bin/Cargo.toml
Bump the new version of catlib that fix mithril dependency issue.
Perform test by running catgateway, work as expected
=> fix(cat-gateway): bump cat lib to r20250509-00

catalyst_voices/apps/voices/lib/widgets/containers/sidebar/sidebar_panel.dart
Fixes clickable side panel when collapsed
Fixes #2512
=> fix(cat-voices): clickable sidebar panel when collapsed

catalyst_voices/apps/voices/lib/widgets/common/simple_tree_view.dart, catalyst_voices/apps/voices/lib/widgets/menu/voices_node_menu.dart, catalyst_voices/apps/voices/lib/widgets/segments/segments_menu.dart
Allows two lines in TreeView elements
Part of #2505  
Before
After
=> fix(cat-voices): allowing two lines in TreeView elements

catalyst-gateway/bin/Cargo.toml, catalyst-gateway/bin/src/db/index/queries/rbac/get_rbac_registrations.rs
Bump the new version of cat-lib which include a fix on `validation _signature` in RBAC registration
=> fix(cat-gateway): bump cat lib to r20250512-00

catalyst-gateway/blueprint.cue
enable signature validation of the RBAC auth token.
=> feat(cat-gateway): disable RBAC_OFF for dev environment

catalyst-gateway/bin/src/db/index/block/rbac509/mod.rs, catalyst-gateway/bin/src/db/index/queries/rbac/get_rbac_registrations.rs
Replaced some logs from `warn` and `error` to `debug` which is more suitable for these cases.
=> feat(cat-gateway): Improve logging

catalyst_voices/apps/voices/lib/common/constants/constants.dart
update url to new value
#2500 
- change link
N/A
N/A
N/A
=> fix(cat-voices): update url in after proposal submission

catalyst-gateway/bin/Cargo.toml, catalyst-gateway/bin/src/db/index/queries/rbac/get_rbac_registrations.rs
=> fix(cat-gateway): bump cat lib tag

catalyst-gateway/tests/api_tests/integration/test_assets.py, catalyst-gateway/tests/api_tests/integration/test_rbac.py, catalyst-gateway/tests/api_tests/integration/test_rbac_auth_token.py, catalyst-gateway/tests/api_tests/integration/test_signed_doc.py, catalyst-gateway/tests/api_tests/poetry.lock, catalyst-gateway/tests/api_tests/pyproject.toml, catalyst-gateway/tests/api_tests/utils/rbac_chain.py, catalyst-gateway/tests/api_tests/utils/signed_doc.py
- Added Catalyst Signed Documents signature validation negative test cases
Closes https://github.com/input-output-hk/catalyst-voices/issues/2217
=> feat(cat-gateway): Catalyst Signed Documents signature negative test cases

catalyst_voices/packages/internal/catalyst_voices_repositories/lib/src/database/database_logging_interceptor.dart
=> chore(cat-voices): do not mark cancellation as error in db interceptor

catalyst_voices/apps/voices/lib/widgets/pagination/layouts/paginated_grid_view.dart
Fixes proposals pagination previous page
=> fix(cat-voices): previous pagination page

catalyst_voices/packages/internal/catalyst_voices_models/lib/src/campaign/campaign_timeline.dart
Opens submission window
> e.g., #1, #1
=> chore: update fund times

catalyst-gateway/bin/Cargo.toml, catalyst-gateway/bin/src/service/api/documents/post_document_index_query/response.rs, catalyst-gateway/tests/api_tests/integration/test_signed_doc.py
=> feat(cat-gateway): Bump cat-libs, Catalyst Signed Docs `parameters` field

catalyst_voices/apps/voices/lib/widgets/document_builder/common/document_property_builder_title.dart, catalyst_voices/apps/voices/lib/widgets/document_builder/value/multiline_text_entry_markdown_widget.dart, catalyst_voices/apps/voices/lib/widgets/document_builder/value/single_dropdown_selection_widget.dart, catalyst_voices/apps/voices/lib/widgets/document_builder/viewer/document_property_builder_viewer.dart, catalyst_voices/apps/voices/lib/widgets/rich_text/voices_rich_text.dart, catalyst_voices/apps/voices/lib/widgets/text_field/token_field.dart, catalyst_voices/apps/voices/lib/widgets/text_field/voices_text_field.dart
As we are making changes to proposal template in #2518 we where needed to update UI.
#2489
- adding placeholders in rich text
- adding labelstyle in token field
N/A
#2518
=> feat(cat-voices): amendments to proposal builder

catalyst-gateway/blueprint.cue, catalyst_voices/blueprint.cue
=> feat: Ingress routing

catalyst_voices/apps/voices/lib/pages/proposal_builder/proposal_builder_validation_snackbar.dart, catalyst_voices/apps/voices/lib/widgets/snackbar/voices_snackbar.dart
Fixes width assert while showing snackbars
=> fix(cat-voices): snackbars width assert

.github/workflows/ci.yml, .github/workflows/flutter-uikit-example-firebase-deploy.yml, .github/workflows/generate-allure-report.yml, .github/workflows/nightly-ci.yml
=> ci(general): updates CI to v1.7.3

catalyst-gateway/blueprint.cue
=> ci(cat-gateway): simplifies routing rules

catalyst-gateway/blueprint.cue
=> ci(general): migrates gateway to statefulset

catalyst-gateway/blueprint.cue
- **ci(general): migrates gateway to statefulset**
- **ci(general): fixes gateway update strategy**
> e.g., #1, #1
=> ci(general): fixes gateway update strategy

catalyst_voices/apps/voices/lib/common/constants/constants.dart, catalyst_voices/apps/voices/lib/pages/dev_tools/widgets/environment_card.dart, catalyst_voices/apps/voices/lib/pages/discovery/sections/stay_involved.dart, catalyst_voices/apps/voices/lib/pages/spaces/drawer/opportunities_drawer.dart, catalyst_voices/packages/internal/catalyst_voices_models/lib/src/config/app_environment.dart, catalyst_voices/packages/internal/catalyst_voices_models/test/config/app_environment_test.dart, catalyst_voices/packages/internal/catalyst_voices_repositories/lib/src/api/api_services.dart
Exposes reviews (app) url base on app env type. This is used to try resolve external urls correctly
=> feat(cat-voices): reviews link resolved against env

catalyst-gateway/blueprint.cue
=> ci(general): fixes cat-gateway metrics scraping

catalyst_voices/packages/internal/catalyst_voices_blocs/lib/src/proposal_builder/proposal_builder_bloc.dart
Fix for "hidden" changed version when editing proposal and in validation mode.
#2670
- making sure that cache and state version of document is in sync
N/A
N/A
N/A
=> fix(cat-voices): validation inputs in proposal builder

.config/dictionaries/project.dic, catalyst_voices/blueprint.cue, catalyst_voices/nginx.conf
=> ci(general): exposes nginx metrics for voices frontend

catalyst_voices/apps/voices/lib/pages/proposal/proposal_page.dart, catalyst_voices/apps/voices/lib/widgets/segments/segments_controller.dart
This pr adds parameter to align scroll position.
#2734 
- added new position parameter to SegmentsController
N/A
https://github.com/user-attachments/assets/79af1c71-f6e8-4f4f-8335-6093eff1df93
N/A
=> feat(cat-voices): add scroll alignment parameter to SegmentsController

catalyst-gateway/bin/src/service/api/documents/templates/data.rs, catalyst-gateway/bin/src/service/api/documents/templates/docs/category/f14_concepts.schema.json, catalyst-gateway/bin/src/service/api/documents/templates/docs/category/f14_developers.schema.json, catalyst-gateway/bin/src/service/api/documents/templates/docs/category/f14_ecosystem.schema.json, catalyst-gateway/bin/src/service/api/documents/templates/docs/category/f14_partner_product.schema.json, catalyst-gateway/bin/src/service/api/documents/templates/docs/f14_proposal_template.schema.json, catalyst-gateway/bin/src/service/api/documents/templates/docs/proposal/f14_concept.schema.json, catalyst-gateway/bin/src/service/api/documents/templates/docs/proposal/f14_developer.schema.json, catalyst-gateway/bin/src/service/api/documents/templates/docs/proposal/f14_ecosystem.schema.json, catalyst-gateway/bin/src/service/api/documents/templates/docs/proposal/f14_partner_product.schema.json, catalyst-gateway/bin/src/service/api/documents/templates/docs/proposal/f14_proposal_template.schema.json
Fix wrong static data. 
GET `api/v1/document/0194d492-1daa-7371-8bd3-c15811b2b063` will return Concept form
#2721
=> fix(cat-gateway): Static document proposal data

catalyst_voices/apps/voices/lib/widgets/cards/proposal/workspace_proposal_card.dart
This PR aling fields in tiles in workspace
#2747
=> fix(cat-voices): align fields in workspace proposal's tiles

catalyst_voices/apps/voices/lib/pages/proposal_builder/appbar/proposal_builder_status_action.dart
Chaing order of checking required steps before publishing. Firstly check email verification, then proposal validation
#2754 
- changing order of checking steps
N/A
N/A
N/A
=> fix(cat-voices): can submit without email verification

catalyst_voices/packages/internal/catalyst_voices_models/lib/src/campaign/campaign_timeline.dart
=> chore: reopen proposal submission

catalyst_voices/apps/voices/lib/common/formatters/date_formatter.dart, catalyst_voices/apps/voices/lib/pages/workspace/submission_closing_warning_dialog.dart, catalyst_voices/apps/voices/lib/widgets/text/proposal_submission_closes_text.dart, catalyst_voices/packages/internal/catalyst_voices_localization/lib/l10n/intl_en.arb, catalyst_voices/packages/internal/catalyst_voices_shared/lib/src/utils/string_ext.dart
Closing submission dialog have new text to make things more readable.
#2781
- changing text
- unifiy date time to 24 format because its used more often across the app
N/A
N/A
=> feat(cat-voices): updating closing submission dialog

catalyst_voices/packages/internal/catalyst_voices_blocs/lib/src/proposal/proposal_cubit.dart
Show full formated name of category.
=> fix(cat-voices): category name in proposal viewer

catalyst_voices/apps/voices/pubspec.yaml, catalyst_voices/melos.yaml, catalyst_voices/packages/internal/catalyst_voices_services/lib/src/logging/logging_service.dart, catalyst_voices/packages/internal/catalyst_voices_services/lib/src/logging/reporting/log_reporting_strategy.dart, catalyst_voices/packages/internal/catalyst_voices_services/lib/src/logging/reporting/sentry_errors_reporting_strategy.dart, catalyst_voices/packages/internal/catalyst_voices_services/pubspec.yaml
Updates sentry plugin and adds reporting errors
Resolves #1926
=> chore(cat-voices): update sentry plugin and reporting

catalyst-gateway/tests/api_tests/test_data/signed_docs/proposal.json
Fixed a used `proposal.json` content for the proposal documents in the integration tests with the latest proposal template schema
=> fix(cat-gateway): Fixed `test_signed_doc.py` integration test

catalyst_voices/apps/voices/lib/pages/dev_tools/widgets/document_ref_field.dart, catalyst_voices/packages/internal/catalyst_voices_view_models/lib/src/document/uuid.dart
Comment template uses V4 version
=> feat(cat-voices): allow any UUID in dev tools lookup

catalyst_voices/blueprint.cue
=> ci(cat-voices): increases replica count to 3

catalyst-gateway/blueprint.cue
=> ci(cat-gateway): increases replicas to 3

catalyst_voices/apps/voices/e2e_tests/.gitignore, catalyst_voices/apps/voices/e2e_tests/data/accountConfigs.ts, catalyst_voices/apps/voices/e2e_tests/data/browserExtensionConfigs.ts, catalyst_voices/apps/voices/e2e_tests/data/walletConfigs.ts, catalyst_voices/apps/voices/e2e_tests/models/accountModel.ts, catalyst_voices/apps/voices/e2e_tests/models/browserExtensionModel.ts, catalyst_voices/apps/voices/e2e_tests/models/testModel.ts, catalyst_voices/apps/voices/e2e_tests/models/walletConfigModel.ts, catalyst_voices/apps/voices/e2e_tests/package-lock.json, catalyst_voices/apps/voices/e2e_tests/package.json, catalyst_voices/apps/voices/e2e_tests/playwright.config.ts, catalyst_voices/apps/voices/e2e_tests/tests/example.spec.ts
This is initial setup for Playwright. The code doesn't touch any other part of the codebase, so it shouldn't change anything at this point.
As description says, it is just a setup for playwright with few useful models that will be used for later test development.
There are no breaking changes./
=> test: Playwright initial setup

catalyst-gateway/bin/src/service/common/auth/rbac/scheme.rs
Update RBAC token validation to use the new `rbac` module.
Closes https://github.com/input-output-hk/catalyst-voices/issues/2433.
=> feat(cat-gateway): Update RBAC token validation

catalyst-gateway/bin/Cargo.toml, catalyst-gateway/tests/api_tests/Earthfile
Bumping cat-libs dependencies to bring up this small fix https://github.com/input-output-hk/catalyst-libs/pull/390
=> feat(cat-gateway): Bumping `cat-libs` dependencies

catalyst-gateway/bin/src/rbac/chain_info.rs, catalyst-gateway/bin/src/rbac/get_chain.rs, catalyst-gateway/bin/src/rbac/mod.rs, catalyst-gateway/bin/src/service/common/auth/rbac/scheme.rs
Return ChainInfo object from `latest_rbac_chain` and `latest_rbac_chain_by_address` functions. This information will be used in the rbac endpoint implementation.
Related to https://github.com/input-output-hk/catalyst-voices/issues/2532.
=> feat(cat-gateway): ChainInfo object

catalyst-gateway/bin/src/rbac/get_chain.rs
Skip special database entries containing information about removed stake addresses. Will be properly fixed as a part of the https://github.com/input-output-hk/catalyst-voices/issues/2599 task.
=> feat(cat-gateway): Temporary fix for removed stake addresses

.config/dictionaries/project.dic, Earthfile, catalyst-gateway/Earthfile, catalyst-gateway/deny.toml, catalyst-gateway/event-db/Earthfile, catalyst-gateway/tests/Earthfile, catalyst-gateway/tests/api_tests/Earthfile, catalyst_voices/Earthfile, catalyst_voices/packages/libs/catalyst_cardano/catalyst_cardano/wallet-automation/Earthfile, catalyst_voices/packages/libs/catalyst_key_derivation/Earthfile, catalyst_voices/packages/libs/catalyst_key_derivation/rust/Earthfile, catalyst_voices/packages/libs/catalyst_key_derivation/rust/deny.toml, catalyst_voices/utilities/uikit_example/Earthfile, docs/Earthfile, utilities/docs-preview/Earthfile
Update ci to v3.4.4
> e.g., #1, #1
=> chore(general): update ci to v3.4.4

catalyst_voices/packages/internal/catalyst_voices_models/lib/src/campaign/campaign_timeline.dart
Update dates for rc4
> e.g., #1, #1
=> chore: update dates

catalyst_voices/apps/voices/pubspec.yaml, catalyst_voices/melos.yaml, catalyst_voices/packages/internal/catalyst_voices_assets/pubspec.yaml, catalyst_voices/packages/internal/catalyst_voices_models/pubspec.yaml, catalyst_voices/packages/internal/catalyst_voices_repositories/pubspec.yaml, catalyst_voices/packages/libs/catalyst_cardano_serialization/pubspec.yaml, catalyst_voices/utilities/uikit_example/pubspec.yaml
Using new version of build_runner and starting to using kirk-check from pub.dev after issue was resolved.
Resolves #2849 
**melos build_runner**
|  | 2.4.12 | 2.5.4 |
|--| ------ | ----- |
|cached|0m14.383s<br>0m14.758s |0m15.589s<br>0m15.743s|
|clean|1m50.979s<br>1m19.839s<br>1m25.497s<br>1m20.950s |1m27.043s<br>1m15.803s |
**melos build_runner_repository**
|  | 2.4.12 | 2.5.4 |
|--| ------ | ----- |
|cached|0m28.417s<br>0m29.674s|0m30.423s<br>0m29.681s|
|clean|0m29.521s<br>0m29.189s<br>0m28.286s |0m34.962s<br>0m29.117s |
We are not the only ones who don't see improvements in build times `https://github.com/dart-lang/build/discussions/4036#discussioncomment-13583306`
N/A
N/A
N/A
=> chore(cat-voices): build runner 2.5.4 update and kirk-check

catalyst_voices/packages/internal/catalyst_voices_models/lib/src/campaign/campaign_timeline.dart
=> chore: update dates for rc6

catalyst_voices/packages/internal/catalyst_voices_models/lib/src/campaign/campaign_category.dart
Remove last description, which is not needed.
Resolves #2986
- removing last description.
- N/A
N/A
N/A
=> feat(cat-voices): removing last category description from Partners and Products

catalyst-gateway/bin/src/metrics/health.rs, catalyst-gateway/bin/src/metrics/mod.rs, catalyst-gateway/bin/src/service/api/cardano/cip36/endpoint.rs, catalyst-gateway/bin/src/service/api/cardano/rbac/registrations_get/mod.rs, catalyst-gateway/bin/src/service/api/health/live_get.rs, catalyst-gateway/bin/src/service/api/health/mod.rs, catalyst-gateway/bin/src/service/api/health/ready_get.rs, catalyst-gateway/bin/src/service/api/health/started_get.rs, catalyst-gateway/bin/src/service/api/mod.rs, catalyst-gateway/bin/src/service/common/responses/mod.rs, catalyst-gateway/bin/src/service/mod.rs, catalyst-gateway/bin/src/service/poem_service.rs, catalyst-gateway/bin/src/service/utilities/middleware/metrics_updater.rs
- Added new health endpoints metric indicators
- Cleaned up `service_unavailable` response processig
Closes #2924
=> feat(cat-gateway): Health endpoint metrics

catalyst-gateway/bin/Cargo.toml
- Bringing a small error messaging update https://github.com/input-output-hk/catalyst-libs/pull/405
=> feat(cat-gateway): Bumping `cat-libs` versions

catalyst_voices/packages/internal/catalyst_voices_models/lib/src/config/app_environment.dart
Getting proper url from relative env of the app
Resolves #3003 
- getting URL base
N/A
N/A
N/A
=> fix(cat-voices): get proper base url for share proposal

catalyst_voices/apps/voices/lib/widgets/pagination/paging_state.dart
Small fix for to value in pagination numbering
Resolves #2993
N/A
N?A
N/A
N/A
=> fix(cat-voices): pagination numbering

.github/workflows/nightly-ci.yml, catalyst-gateway/tests/schemathesis_tests/Earthfile, catalyst-gateway/tests/schemathesis_tests/blueprint.cue, catalyst_voices/packages/libs/catalyst_cardano/catalyst_cardano/wallet-automation/Earthfile, catalyst_voices/packages/libs/catalyst_cardano/catalyst_cardano/wallet-automation/blueprint.cue
Disable nightly ci targets and make nightly run only manually until we fix the nightly tests
> e.g., #1, #1
=> fix: disable nightly ci

catalyst-gateway/bin/src/metrics/caches/native_assets.rs, catalyst-gateway/bin/src/metrics/caches/txo_assets.rs
Add correct descriptions to metrics for caches.
#2925
=> fix(cat-gateway): Cache metric descriptions update

catalyst-gateway/blueprint.cue, catalyst_voices/blueprint.cue
=> ci(general): constrains resources and allows more fields to be overwritten

catalyst-gateway/bin/Cargo.toml, catalyst-gateway/bin/src/db/index/queries/rbac/get_catalyst_id_from_public_key.rs, catalyst-gateway/bin/src/db/index/queries/rbac/get_catalyst_id_from_stake_address.rs, catalyst-gateway/bin/src/db/index/queries/rbac/get_catalyst_id_from_transaction_id.rs, catalyst-gateway/bin/src/rbac/get_chain.rs, catalyst-gateway/bin/src/rbac/validation.rs
Small code cleanup related to RBAC caches.
Closes https://github.com/input-output-hk/catalyst-voices/issues/2980.
https://github.com/input-output-hk/catalyst-libs/pull/421
https://github.com/input-output-hk/catalyst-voices/pull/3047
=> feat(cat-gateway): Cleanup RBAC caches (Arc inside CatalystID)

catalyst_voices/packages/internal/catalyst_voices_localization/lib/l10n/intl_en.arb
Copy text change to approval contingency... 
Closes #3057 
- update copy text
N/A
N/A
N/A
=> feat(cat-voices):  copy text update to drep approval contingency

.github/workflows/branch-delete-cleanup.yml, .github/workflows/ci.yml, .github/workflows/flutter-uikit-example-firebase-deploy.yml, .github/workflows/generate-allure-report.yml, .github/workflows/nightly-ci.yml, .github/workflows/semantic_pull_request.yml, .github/workflows/sync-labels.yml, blueprint.cue
=> ci(general): bumps forge to 0.19.0 and ci to 1.8.0

catalyst_voices/packages/internal/catalyst_voices_blocs/lib/src/registration/registration_cubit.dart, catalyst_voices/packages/internal/catalyst_voices_models/lib/src/registration/account_submit_data.dart, catalyst_voices/packages/internal/catalyst_voices_services/lib/src/registration/registration_service.dart, catalyst_voices/packages/internal/catalyst_voices_services/lib/src/registration/registration_transaction_builder.dart, catalyst_voices/packages/internal/catalyst_voices_services/lib/src/registration/strategy/registration_transaction_strategy.dart, catalyst_voices/packages/internal/catalyst_voices_services/lib/src/registration/strategy/registration_transaction_strategy_bytes.dart, catalyst_voices/packages/internal/catalyst_voices_services/lib/src/registration/strategy/registration_transaction_strategy_models.dart, catalyst_voices/packages/internal/catalyst_voices_services/lib/src/registration/strategy/registration_transaction_strategy_type.dart, catalyst_voices/packages/internal/catalyst_voices_services/test/src/registration/registration_transaction_builder_test.dart, catalyst_voices/packages/internal/catalyst_voices_services/test/src/registration/strategy/registration_transaction_strategy_test.dart, catalyst_voices/packages/libs/catalyst_cardano/catalyst_cardano_platform_interface/lib/src/cardano_wallet.dart, catalyst_voices/packages/libs/catalyst_cardano/catalyst_cardano_web/lib/src/interop/catalyst_cardano_wallet_proxy.dart, catalyst_voices/packages/libs/catalyst_cardano_serialization/lib/src/transaction.dart
Just prepare for bytes registration transaction strategy
=> feat(cat-voices): registration transaction strategy

.config/dictionaries/project.dic, .github/workflows/ci.yml, .github/workflows/flutter-uikit-example-firebase-deploy.yml, .github/workflows/generate-allure-report.yml, .github/workflows/nightly-ci.yml, .github/workflows/sync-labels.yml, blueprint.cue
=> ci(general): bumps forge to v0.19.1 and ci to v1.8.1

.config/dictionaries/project.dic, catalyst-gateway/blueprint.cue, config/Earthfile, config/blueprint.cue, config/dev/settings.json, config/entrypoint.sh, config/preprod/settings.json, config/prod/settings.json
=> ci(config): packages config script into k8s job

catalyst-gateway/blueprint.cue
=> ci(general): drops hash from gateway job names

.config/dictionaries/project.dic, .github/workflows/ci.yml, .github/workflows/flutter-uikit-example-firebase-deploy.yml, .github/workflows/generate-allure-report.yml, .github/workflows/nightly-ci.yml, blueprint.cue, catalyst_voices/packages/libs/catalyst_cardano/catalyst_cardano/wallet-automation/blueprint.cue
=> ci(general): bumps forge to v0.21.0, ci to v1.10.0, and adds Earthfile reject job

Earthfile, catalyst-gateway/event-db/Earthfile, catalyst-gateway/tests/Earthfile, catalyst-gateway/tests/api_tests/Earthfile, catalyst_voices/Earthfile, catalyst_voices/packages/libs/catalyst_cardano/catalyst_cardano/wallet-automation/Earthfile, catalyst_voices/packages/libs/catalyst_key_derivation/Earthfile, catalyst_voices/utilities/uikit_example/Earthfile, docs/Earthfile, utilities/docs-preview/Earthfile
=> chore: update ci to v3.5.2

catalyst-gateway/bin/src/service/api/documents/post_document_index_query/v1/mod.rs, catalyst-gateway/bin/src/service/api/documents/post_document_index_query/v2/mod.rs
Fix `v1/document/index` and `v2/document/index` endpoints
=> fix(cat-gateway): Fix `document/index` endpoints

catalyst-gateway/bin/Cargo.toml, catalyst-gateway/bin/src/rbac/get_chain.rs, catalyst-gateway/bin/src/rbac/validation.rs
- Update the `rbac-registration` dependency to `0.0.7` version.
=> chore(cat-gateway): Update the `rbac-registration` dependency to `0.0.7` version

catalyst_voices/apps/voices/lib/dependency/dependencies.dart, catalyst_voices/apps/voices/lib/pages/proposal/tiles/proposal_voting_overview.dart, catalyst_voices/apps/voices/lib/pages/spaces/appbar/voting/vote_list_button.dart, catalyst_voices/packages/internal/catalyst_voices_blocs/lib/src/proposal/proposal_cubit.dart, catalyst_voices/packages/internal/catalyst_voices_blocs/lib/src/proposal/proposal_cubit_cache.dart, catalyst_voices/packages/internal/catalyst_voices_blocs/lib/src/proposals/proposals_cubit.dart, catalyst_voices/packages/internal/catalyst_voices_blocs/lib/src/proposals/proposals_cubit_cache.dart, catalyst_voices/packages/internal/catalyst_voices_blocs/lib/src/voting/voting_cubit.dart, catalyst_voices/packages/internal/catalyst_voices_blocs/lib/src/voting/voting_cubit_cache.dart, catalyst_voices/packages/internal/catalyst_voices_blocs/lib/src/voting_ballot/voting_ballot_bloc.dart, catalyst_voices/packages/internal/catalyst_voices_blocs/lib/src/voting_ballot/voting_ballot_cache.dart, catalyst_voices/packages/internal/catalyst_voices_blocs/lib/src/voting_ballot/voting_ballot_state.dart, catalyst_voices/packages/internal/catalyst_voices_blocs/lib/src/workspace/workspace_bloc.dart, catalyst_voices/packages/internal/catalyst_voices_models/lib/src/campaign/campaign_category.dart, catalyst_voices/packages/internal/catalyst_voices_models/lib/src/proposal/proposal_with_context.dart, catalyst_voices/packages/internal/catalyst_voices_models/lib/src/voting/vote.dart, catalyst_voices/packages/internal/catalyst_voices_models/lib/src/voting/vote_proposal.dart, catalyst_voices/packages/internal/catalyst_voices_repositories/lib/src/voting/voting_repository.dart, catalyst_voices/packages/internal/catalyst_voices_services/lib/src/proposal/proposal_service.dart, catalyst_voices/packages/internal/catalyst_voices_services/lib/src/voting/voting_service.dart, catalyst_voices/packages/internal/catalyst_voices_services/test/src/proposal/proposal_service_test.dart, catalyst_voices/packages/internal/catalyst_voices_view_models/lib/src/proposal/proposal_brief.dart, catalyst_voices/packages/internal/catalyst_voices_view_models/lib/src/proposal/proposal_view_voting.dart
This adds connection between ballot builder and voting service
N/A
- adding connection between ballot builder and voting service
N/A
https://github.com/user-attachments/assets/80713b47-123d-49e7-9830-c8ae42d239a0
N/A
=> feat(cat-voices):  voting service to ballot builder

catalyst-gateway/bin/Cargo.toml
Updating the fixed version of the `cardano-chain-follower`, which fixes an issue with not correctly reporting to mithril updates, which affects metrics of the cat-gateway
Closes https://github.com/input-output-hk/catalyst-voices/issues/2950
- Updating to the fixed version of `cardano-chain-follower` crate
https://github.com/input-output-hk/catalyst-libs/pull/467
=> fix(cat-gateway): bump `cardano-chain-follower`

catalyst_voices/apps/voices/lib/pages/voting/widgets/grid/voting_proposals_pagination_tile.dart, catalyst_voices/apps/voices/lib/widgets/cards/proposal/proposal_brief_card.dart, catalyst_voices/apps/voices/lib/widgets/voting/vote_button.dart, catalyst_voices/apps/voices/lib/widgets/voting/vote_button_expanded.dart
Adding read view mode for voting button
Closes #3212 
- N/A
N/A
https://github.com/user-attachments/assets/1029c78d-e69a-4219-971a-afe2fbaabacc
N/A
=> feat(cat-voices): read only vote button

catalyst_voices/apps/voices/lib/pages/account/account_page.dart, catalyst_voices/apps/voices/lib/pages/account/widgets/account_keychain_tile.dart, catalyst_voices/apps/voices/lib/pages/proposal/proposal_page.dart, catalyst_voices/apps/voices/lib/pages/registration/account_completed/account_completed_panel.dart, catalyst_voices/apps/voices/lib/pages/registration/recover/seed_phrase/restored_panel.dart, catalyst_voices/apps/voices/lib/pages/spaces/appbar/spaces_appbar/voting_appbar.dart, catalyst_voices/apps/voices/lib/pages/spaces/appbar/voting/voting_leading_button.dart, catalyst_voices/apps/voices/lib/pages/voting/voting_page.dart, catalyst_voices/apps/voices/lib/pages/voting/widgets/content/pre_voting_content.dart, catalyst_voices/apps/voices/lib/pages/voting/widgets/grid/voting_proposals_tabs.dart, catalyst_voices/apps/voices/lib/pages/voting/widgets/header/voting_general_header.dart, catalyst_voices/apps/voices/lib/pages/voting/widgets/header/voting_header.dart, catalyst_voices/apps/voices/lib/routes/routing/spaces_route.dart, catalyst_voices/apps/voices/lib/widgets/indicators/voices_linear_progress_indicator.dart, catalyst_voices/apps/voices/lib/widgets/layouts/header_and_content_layout.dart, catalyst_voices/apps/voices/lib/widgets/tabbar/voices_tab.dart, catalyst_voices/apps/voices/lib/widgets/tabbar/voices_tab_bar.dart, catalyst_voices/packages/internal/catalyst_voices_blocs/lib/src/campaign/campaign_phase/campaign_phase_aware_state.dart, catalyst_voices/packages/internal/catalyst_voices_blocs/lib/src/proposal/proposal_cubit.dart, catalyst_voices/packages/internal/catalyst_voices_blocs/lib/src/proposal/proposal_cubit_cache.dart, catalyst_voices/packages/internal/catalyst_voices_blocs/lib/src/session/session_state.dart, catalyst_voices/packages/internal/catalyst_voices_blocs/lib/src/voting/voting_state.dart, catalyst_voices/packages/internal/catalyst_voices_localization/lib/l10n/intl_en.arb, catalyst_voices/packages/internal/catalyst_voices_view_models/lib/src/authentication/access_control.dart
Minor adjustments found while testing
- hide unnecessary widgets from pre voting layout
- clearing proposal cubit on initState
- hiding leading app bar action for votingAppbar
- clipping progress bar correctly
- hide category picker in pre voting
=> chore(cat-voices): minor adjustments

catalyst_voices/packages/internal/catalyst_voices_repositories/lib/src/document/source/document_data_remote_source.dart
Workaround for V1 document index endpoint bug.
#3199
=> chore(cat-voices): workaround for v1 document index bug

catalyst_voices/packages/internal/catalyst_voices_models/lib/src/config/app_config.dart, catalyst_voices/packages/internal/catalyst_voices_repositories/lib/src/config/app_config_factory.dart, catalyst_voices/packages/internal/catalyst_voices_repositories/lib/src/dto/config/remote_sentry_config.dart, catalyst_voices/packages/internal/catalyst_voices_services/lib/src/config/config_service.dart, config/dev/config.json, config/preprod/config.json, config/prod/config.json
Overrides `debug` sentry config to equal kDebugMode
=> chore(cat-voices): safety check sentry config

catalyst-gateway/Earthfile, catalyst-gateway/tests/Earthfile
- optimise rust-tests-runner size (2GB -> 0.2GB)
- fix gateway build for arm hosts
> e.g., #1, #1
=> chore(cat-gateway): Fix gateway build for arm

.config/dictionaries/project.dic, catalyst-gateway/bin/Cargo.toml, catalyst-gateway/bin/src/cli.rs, catalyst-gateway/bin/src/db/event/mod.rs, catalyst-gateway/bin/src/db/event/signed_docs/tests/mod.rs, catalyst-gateway/bin/src/service/common/responses/mod.rs, catalyst-gateway/bin/src/settings/event_db.rs, catalyst-gateway/bin/src/settings/mod.rs, catalyst-gateway/bin/src/settings/str_env_var.rs
- Applied changes from these PRs https://github.com/input-output-hk/catalyst-voices/pull/3290 and https://github.com/input-output-hk/catalyst-voices/pull/3341 to the F15 release
Closes #3428
=> fix(cat-gateway): Migrate EventDB from `bb8` to `deadpool`

.github/workflows/gateway-tests.yml, catalyst-gateway/tests/api_tests/Earthfile
=> chore(cat-gateway): Add gateway logs if sync failed

catalyst-gateway/Earthfile, catalyst-gateway/bin/src/db/index/queries/mod.rs, catalyst-gateway/bin/src/service/api/cardano/cip36/endpoint.rs, catalyst-gateway/bin/src/service/common/types/cardano/query/as_at.rs, catalyst-gateway/tests/api_tests/Earthfile
Fixing CI f15 cat-gateway issues
=> fix(cat-gateway): Fix `cat-gateway` f15 CI build

catalyst-gateway/blueprint.cue
Cleaning up `cat-gateway` `event-db` env configuration settings.
=> feat(cat-gateway): Set the `event-db` configuration env vars 

catalyst_voices/Earthfile, catalyst_voices/blueprint.cue, catalyst_voices/packages/libs/catalyst_key_derivation/rust/Earthfile
This feature branch `f15/cat-gateway` contains *only* `cat-gateway` release candidate code.
By disabling frontend related earthly targets it speed up the CI  and development process.
=> feat(general): Disable FE `earthly` targets

catalyst_voices/packages/internal/catalyst_voices_blocs/lib/src/proposal/proposal_cubit.dart, catalyst_voices/packages/internal/catalyst_voices_blocs/lib/src/proposal_builder/proposal_builder_bloc.dart, catalyst_voices/packages/internal/catalyst_voices_models/lib/src/document/specialized/comment_document.dart, catalyst_voices/packages/internal/catalyst_voices_repositories/lib/src/comment/comment_repository.dart
Includes proposal `category_id` when publishing comment
- #3467
- Blocked by #3466
=> chore(cat-voices): comments category_id

catalyst_voices/blueprint.cue
=> fix(cat-voices): sentry auth token in docker target

catalyst-gateway/Cargo.lock, catalyst-gateway/bin/Cargo.toml, catalyst-gateway/tests/api_tests/integration/test_signed_doc.py
- Applying latest validation rules from https://github.com/input-output-hk/catalyst-libs/releases/tag/catalyst-signed-doc%2Fv0.0.4-f15-rc-2 release.
- Added more integration tests cases.
=> feat(cat-gateway): Latest Catalyst Signed Documents validation rules from `catalyst-signed-doc/v0.0.4-f15-rc-2` 
