input-output-hk/catalyst-voices

- catalyst-gateway/bin/src/event_db/error.rs
- catalyst-gateway/bin/src/event_db/mod.rs
- catalyst-gateway/bin/src/event_db/queries/event/ballot.rs
- catalyst-gateway/bin/src/event_db/queries/event/proposal.rs
- catalyst-gateway/bin/src/event_db/queries/event/review.rs
- catalyst-gateway/bin/src/event_db/queries/mod.rs
- catalyst-gateway/bin/src/event_db/types/proposal.rs
- catalyst-gateway/bin/src/service/api/health/mod.rs
- catalyst-gateway/bin/src/service/api/health/ready_get.rs
- catalyst-gateway/bin/src/state/mod.rs
Ensure DB Schema mismatch between the service and DB does not cause the service to fail.
Resolves https://github.com/input-output-hk/catalyst-voices/issues/46
Modifies `GET api/health/ready` to validate that not only is the database connected, but that the schema version is the one the application expects.
> feat:  cat-gateway must be resiliant in the face of DB schema changes

- catalyst-gateway/Cargo.toml
- catalyst-gateway/bin/Cargo.toml
This is a small cleanup to consolidate project metadata into the workspace.
Developers are encouraged to add themselves to `authors` in their next PR for catalyst-gateway code.
> chore(gateway): Move metadata to the workspace for cat-gateway

- catalyst-gateway/event-db/stage_data/dev/00001_testfund_event.sql
- catalyst-gateway/event-db/stage_data/dev/00002_testfund_ideascale_params.sql
- catalyst-gateway/event-db/stage_data/testnet/00001_fund10_event.sql
- catalyst-gateway/event-db/stage_data/testnet/00002_fund10_ideascale_params.sql
Fix duplicate key errors by changing stage_data SQL statements to upsert event and config data instead of inserting.
Same change I did in `catalyst-core` https://github.com/input-output-hk/catalyst-core/pull/624.
https://github.com/input-output-hk/catalyst-core/issues/500
> chore(fix-stage-data-sql): Upsert event-db stage data

- .config/dictionaries/project.dic
- catalyst_voices/packages/catalyst_voices_assets/internal_resources/README.md
- docs/src/architecture/09_architecture_decisions/0003-flutter.md
- docs/src/architecture/09_architecture_decisions/index.md
- Add ADR on why we decided to use Flutter
- Add the `internal_resources`  folder to `catalyst_voices_assets`
Closes #161 
None
Not applicable
> feat: add flutter adr, update catalyst_voices_assets

- catalyst-gateway/Earthfile
Remove `CP_SRC` UDC is a redundant command that could be replaced by the common `COPY` command.
> e.g., Closes #180 
* Removed `CP_SRC` UDC
> chore: use `COPY` command instead of `CP_SRC`

- catalyst-gateway/bin/src/service/api/health/ready_get.rs
- catalyst-gateway/bin/src/state/mod.rs
Updates `catalyst-gateway` service `GET /health/ready` endpoint, such that when a DB schema version mismatch happens, the service becomes unavailable, and should recover when the expected version is in place.
Closes #47
> feat: Handle DB schema version mismatch

- .config/dictionaries/project.dic
- catalyst-gateway/.cargo/config.toml
- catalyst-gateway/.config/nextest.toml
- catalyst-gateway/Cargo.lock
- catalyst-gateway/Cargo.toml
- catalyst-gateway/Earthfile
- catalyst-gateway/bin/Cargo.toml
- catalyst-gateway/bin/src/event_db/error.rs
- catalyst-gateway/bin/src/event_db/queries/event/ballot.rs
- catalyst-gateway/bin/src/event_db/queries/event/mod.rs
- catalyst-gateway/bin/src/event_db/queries/event/proposal.rs
- catalyst-gateway/bin/src/event_db/queries/registration.rs
- catalyst-gateway/bin/src/event_db/queries/search.rs
- catalyst-gateway/bin/src/event_db/queries/vit_ss/fund.rs
- catalyst-gateway/bin/src/event_db/types/registration.rs
- catalyst-gateway/bin/src/event_db/types/vit_ss/challenge.rs
- catalyst-gateway/bin/src/event_db/types/vit_ss/fund.rs
- catalyst-gateway/bin/src/event_db/types/vit_ss/goal.rs
- catalyst-gateway/bin/src/event_db/types/vit_ss/group.rs
- catalyst-gateway/bin/src/service/api/mod.rs
- catalyst-gateway/bin/src/service/common/objects/voter_registration.rs
- catalyst-gateway/bin/src/service/utilities/middleware/tracing_mw.rs
- catalyst-gateway/deny.toml
- catalyst-gateway/rust-toolchain.toml
- catalyst-gateway/tests/Cargo.toml
- catalyst-gateway/tests/Earthfile
- catalyst-gateway/tests/integration/catalyst_gateway_event_db.rs
- catalyst-gateway/tests/integration/main.rs
- docs/Earthfile
Update poems' related dependencies.
- Update 
- poem to v2.0.0
- poem-openapi to v4.0.0
- poem-extensions to v0.8.0
- Fix all issues related to the updates
- Ignoring the integration test for now because of the network connection panic
Updating Rust to a stable version 1.75.0 and other dependencies causes some syntax changes
> fix: update poems

- catalyst_voices/android/build.gradle
-  bump kotlin version 1.9.22 to fix compatibility issues with the latest Flutter version
> chore: bump kotlin version

- catalyst-gateway/tests/Earthfile
This PR adds a line to pretty print the cat gateway logs on screen in case of schemathesis test fail
> e.g., #123, #456
> feat: Printing cat gateway logs in case of failure

- catalyst-gateway/Earthfile
Adding `--if-exists` to `save artifact` after the build script is run. This is because is something fails in the build script earthly fails saying it cannot find the artifact to save. For example when the tests fail the coverage file is not produced 
> e.g., #123, #456
> fix: Adds --if-exists to save artifacts

- catalyst-gateway/Cargo.lock
- catalyst-gateway/Cargo.toml
- catalyst-gateway/bin/Cargo.toml
- catalyst-gateway/bin/src/cli.rs
- catalyst-gateway/bin/src/follower.rs
- catalyst-gateway/bin/src/logger.rs
- catalyst-gateway/bin/src/util.rs
Added the `anyhow` dependency and update some places to use this lib.
> refactor: Add `anyhow` error handling

- catalyst_voices/Earthfile
> build(catalyst_voices): fixes Earthfile and adds publish target

- catalyst_voices/packages/catalyst_voices_shared/lib/src/responsive/responsive_builder.dart
Optimizes usage of MediaQuery to subscribe to only required changes in MediaQuery.
> perf: Optimize media query usage to avoid redundant rebuilds

- catalyst-gateway/bin/src/cli.rs
- catalyst-gateway/bin/src/event_db/error.rs
- catalyst-gateway/bin/src/event_db/mod.rs
- catalyst-gateway/bin/src/service/api/cardano/date_time_to_slot_number_get.rs
- catalyst-gateway/bin/src/service/api/cardano/registration_get.rs
- catalyst-gateway/bin/src/service/api/cardano/staked_ada_get.rs
- catalyst-gateway/bin/src/service/api/cardano/sync_state_get.rs
- catalyst-gateway/bin/src/service/api/health/ready_get.rs
- catalyst-gateway/bin/src/service/mod.rs
- catalyst-gateway/bin/src/service/utilities/middleware/schema_validation.rs
- catalyst-gateway/bin/src/state/mod.rs
- catalyst-gateway/tests/api_tests/api_tests/__init__.py
- Update service `State` struct, removed `schema_version_status` field.
- Modified `SchemaVersionValidation` middleware, made an explicit check of the even-db version.
- Clean up endpoints
Closes https://github.com/input-output-hk/catalyst-voices/issues/412
> refactor: update schema_validation check

- catalyst_voices/Earthfile
Locks a specific flutter version during Earthfile builds on the CI. Currently every build targets the latest flutter version, since 3.22.0 has just been released the builds are not working.
Incrementing flutter version should be intentional and tested, not automatic.
Note:
- I have investigated if it's easily possible to extract the flutter version from melos.yaml where we define it but it would require manually parsing .yaml file and looking for a specific key. If there will be a suggestion to do it, I'll work on it but the point of the PR is to make CI working again as fast as possible.
> feat: lock specific flutter version on ci

- .config/dictionaries/project.dic
- catalyst-gateway/Earthfile
- catalyst-gateway/event-db/Earthfile
- catalyst-gateway/tests/api_tests/Earthfile
- utilities/local-cluster/.vagrant/rgloader/loader.rb
> feat: bump ci to 3.00.1

- .config/dictionaries/project.dic
- .github/workflows/generate-allure-report.yml
- catalyst-gateway/tests/api_tests/.gitignore
- catalyst-gateway/tests/api_tests/Earthfile
Modify the python backend tests that are runned using pytest to generate a junit test report and integrate them with the allure report workflow
- generate xml junit report to the earthly [test target](https://github.com/input-output-hk/catalyst-voices/blob/d00fa4a8159bff34322ec8e8949aee865fa3e213/catalyst-gateway/tests/api_tests/Earthfile#L14)
- add the report to the [allure workflow](https://github.com/input-output-hk/catalyst-voices/blob/main/.github/workflows/generate-allure-report.yml)
> feat: create test reporting for backend python tests

- catalyst-gateway/tests/schemathesis_tests/Earthfile
Increased `schemathesis` max response time limit to 5 seconds.
> fix(ci): Increase schemathesis max response time

- catalyst_voices/uikit_example/lib/examples_list.dart
- catalyst_voices/uikit_example/lib/main.dart
Adds theme mode switcher between light/dark theme to UIKit example app.
> feat: add theme mode switcher

- .github/workflows/flutter-uikit-example-firebase-deploy.yml
- catalyst_voices/test_driver/Earthfile
- catalyst_voices/uikit_example/Earthfile
UI Kit earthly target only needs to be triggered by a specific github action that consumes the target output files to deploy the app on firebase hosting. Renaming it so that it doesn't get discovered and run by catalyst-ci.
> fix: don't trigger uikit deploy needlessly

- catalyst_voices/lib/widgets/chips/voices_chip.dart
Fixes icon theme for leading/trailing in the VoicesChip to make sure they have enough contrast in light/dark mode.
> fix: chips light/dark icons

- catalyst_voices/Earthfile
- catalyst_voices/uikit_example/Earthfile
Adds earthly check for validating that dart/flutter publishable packages can be published without issues to pub.dev.
> feat: add check for publishable packages

- catalyst_voices/pubspec.yaml
- catalyst_voices_packages/catalyst_analysis/README.md
- catalyst_voices_packages/catalyst_cardano/catalyst_cardano/README.md
- catalyst_voices_packages/catalyst_cardano_serialization/README.md
- Removes any explicit package versions in favor of using latest version in README files to avoid manually updating these after each release. Melos can't do it automatically.
- Updates catalyst_voices to use catalyst_analysis from path instead of hardcoded version
> fix: readme versioning for catalyst packages

- catalyst_voices/Earthfile
- catalyst_voices/uikit_example/Earthfile
Updates catalyst-ci to 3.1.12 that addresses the missing chromium version: https://github.com/input-output-hk/catalyst-ci/releases/tag/v3.1.12
> fix: missing chromium version

- .github/workflows/flutter-publish-packages.yml
- catalyst_voices_packages/catalyst_cardano/catalyst_cardano/pubspec.yaml
- catalyst_voices_packages/catalyst_cardano/catalyst_cardano_platform_interface/example/main.dart
- catalyst_voices_packages/catalyst_cardano/catalyst_cardano_web/example/main.dart
- catalyst_voices_packages/catalyst_cardano/catalyst_cardano_web/pubspec.yaml
- catalyst_voices_packages/catalyst_cardano_serialization/pubspec.yaml
- melos.yaml
- Adds a github action that publishes dart/flutter packages to pub.dev when [triggered manually](https://docs.github.com/en/actions/using-workflows/manually-running-a-workflow) on github actions. The action will also create a PR with changelogs, this is the recommended workflow from the [melos team](https://github.com/marketplace/actions/melos-action#2-directly-publish-to-pubdev-after-each-pr-is-merged).
- Fixes issues that lower the pub.dev score of packages
Closes #494
> feat: automate melos release

- Earthfile
- catalyst-gateway/Earthfile
- catalyst-gateway/deny.toml
- catalyst-gateway/event-db/Earthfile
- catalyst-gateway/tests/Earthfile
- catalyst-gateway/tests/api_tests/Earthfile
- catalyst_voices/Earthfile
- catalyst_voices/uikit_example/Earthfile
- docs/Earthfile
> fix: update cat-ci version to 3.1.13

- .github/workflows/nightly-ci.yml
- Fix report folder name so that results are not in same folder with CI run
- Add manual trigger for nightly ci
> fix: report folder name, trigger manual

- catalyst_voices_packages/catalyst_cardano/catalyst_cardano/README.md
- catalyst_voices_packages/catalyst_cardano/catalyst_cardano/example/lib/main.dart
- catalyst_voices_packages/catalyst_cardano/catalyst_cardano/example/lib/sign_and_submit_rbac_tx.dart
- catalyst_voices_packages/catalyst_cardano/catalyst_cardano/example/lib/sign_and_submit_tx.dart
- catalyst_voices_packages/catalyst_cardano/catalyst_cardano_platform_interface/lib/src/cardano_wallet.dart
- catalyst_voices_packages/catalyst_cardano/catalyst_cardano_web/assets/js/catalyst_cardano.js
- catalyst_voices_packages/catalyst_cardano/catalyst_cardano_web/lib/src/interop/catalyst_cardano_interop.dart
- catalyst_voices_packages/catalyst_cardano/catalyst_cardano_web/lib/src/interop/catalyst_cardano_wallet_proxy.dart
Workarounds and various fixes to make it possible to work with [Typhoon wallet](https://typhonwallet.io/#/).
The CIP-30 implementation by that wallet distinguishes between `null` and `undefined` and behaves wrongly when it expects `undefined` but gets `null`. CIP-30 prefers using `undefined` values while dart converts `nulls` into JS `null`. Lets then make sure we send them `undefined`.
Additionally `supportedExtensions` getter and `getSupportedExtensions` method has not been implemented at all by that wallet even though it is required by CIP-30. Since the method is not critical the package will return default values.
> fix: catalyst cardano integration with Typhoon wallet

- .config/dictionaries/project.dic
- catalyst_voices_packages/catalyst_cardano/catalyst_cardano/example/lib/sign_and_submit_rbac_tx.dart
- catalyst_voices_packages/catalyst_cardano_serialization/lib/catalyst_cardano_serialization.dart
- catalyst_voices_packages/catalyst_cardano_serialization/lib/src/certificate.dart
- catalyst_voices_packages/catalyst_cardano_serialization/lib/src/hashes.dart
- catalyst_voices_packages/catalyst_cardano_serialization/lib/src/rbac/registration_data.dart
- catalyst_voices_packages/catalyst_cardano_serialization/lib/src/rbac/x509_metadata_envelope.dart
- catalyst_voices_packages/catalyst_cardano_serialization/lib/src/signature.dart
- catalyst_voices_packages/catalyst_cardano_serialization/lib/src/transaction.dart
- catalyst_voices_packages/catalyst_cardano_serialization/lib/src/utils/cbor.dart
- catalyst_voices_packages/catalyst_cardano_serialization/lib/src/utils/uuid.dart
- catalyst_voices_packages/catalyst_cardano_serialization/test/hashes_test.dart
- catalyst_voices_packages/catalyst_cardano_serialization/test/utils/uuid_test.dart
Addresses wrong assumptions and mistakes in X509 encoding as requested by @stevenj.
```
a11901fda50050ca7a1457ef9f4c7f9c747f8c4a4cfa6c01582093e454212640048731a87b0f62dc16495e02eb1d3a36fe199fcd1af4c2540d5e0258204d3f576f26db29139981a69443c2325daa812cc353a31b5a4db794a5bcbb06c20b8c58401b3e030866084fcb259de07496d3197e913a39fd628a3db0a4ed6839261a00c51cb0a5b9c16194064132cc5b77ea23c75c60659400cba304d0d689c00086195d5840ff28714da02c35e7295815ba58b77f227e576fa254c464e2f9c6f9dfa900a0208250033c054a468c38e08819601d073c034a4727a524ef9c4cea77443c1fca235840839c927599b253887f50487c1caf757c0aaf79bc3fcacd42252b8f2ae1f1a8b282929ca22bb5c2885cc23a66005c0cc1ca20142b82310c3a137d44c1943e40995840a7a7ce5c3475b5887a3765ede2ff3b7bfea90f255e2edf37fd44e27f26b8e6cf408aef4b20bebf7257b3dabc7eda65fff4ed278b50219f0a52367ff5b8 …
```
> fix!: X509 registration metadata encoding

- catalyst_voices_packages/catalyst_cardano/catalyst_cardano/example/lib/sign_data.dart
- catalyst_voices_packages/catalyst_cardano/catalyst_cardano_platform_interface/lib/src/cardano_wallet.dart
- catalyst_voices_packages/catalyst_cardano/catalyst_cardano_web/lib/src/interop/catalyst_cardano_interop.dart
- catalyst_voices_packages/catalyst_cardano/catalyst_cardano_web/lib/src/interop/catalyst_cardano_wallet_proxy.dart
Fixes wrong return type from CIP-30 signData method. The data is encoded as JSON, not as CBOR.
Expected result in example app after calling signData:
> fix!: signData return type should be DataSignature, not VkeyWitness

- catalyst_voices_packages/catalyst_cardano_serialization/lib/src/hashes.dart
- catalyst_voices_packages/catalyst_cardano_serialization/lib/src/rbac/x509_metadata_envelope.dart
- catalyst_voices_packages/catalyst_cardano_serialization/test/hashes_test.dart
Updates transaction inputs hash size from 32 to 16 bytes. Adds missing tests.
> feat!: update transactions inputs hash size

- catalyst_voices/lib/widgets/buttons/voices_button_affix_decoration.dart
- catalyst_voices/lib/widgets/buttons/voices_filled_button.dart
- catalyst_voices/lib/widgets/buttons/voices_icon_button.dart
- catalyst_voices/lib/widgets/buttons/voices_outlined_button.dart
- catalyst_voices/lib/widgets/buttons/voices_text_button.dart
- catalyst_voices/lib/widgets/chips/voices_chip.dart
- catalyst_voices/lib/widgets/common/affix_decorator.dart
- catalyst_voices/lib/widgets/common/prefix_suffix_decorator.dart
- catalyst_voices/lib/widgets/widgets.dart
- catalyst_voices/packages/catalyst_voices_blocs/pubspec.yaml
- catalyst_voices/packages/catalyst_voices_brands/lib/src/themes/catalyst.dart
- catalyst_voices/packages/catalyst_voices_brands/lib/src/themes/widgets/buttons_theme.dart
- catalyst_voices/uikit_example/lib/examples/voices_buttons_example.dart
- catalyst_voices/uikit_example/lib/examples_list.dart
- catalyst_voices/uikit_example/pubspec.yaml
- melos.yaml
- Add all variants of `VoicesButtons*` for Catalyst Voice frontend
https://github.com/user-attachments/assets/526e8689-41cd-41a5-a744-3ac89db10154
Closes #651 
- Introduce `AffixDecorator` widget which encapsulates repeatable logic in all buttons as well as in  `VoicesChip`
> feat: VoicesButtons

- catalyst_voices_packages/catalyst_cardano/catalyst_cardano/example/lib/sign_and_submit_rbac_tx.dart
- catalyst_voices_packages/catalyst_cardano_serialization/lib/src/hashes.dart
- catalyst_voices_packages/catalyst_cardano_serialization/test/hashes_test.dart
Transaction inputs hash should be generated only from the UTXO inputs, not from the whole UTXO that contains outputs too.
> fix: rbac txn inputs hash

- catalyst_voices/lib/widgets/text_field/voices_email_text_field.dart
- catalyst_voices/lib/widgets/text_field/voices_password_text_field.dart
- catalyst_voices/lib/widgets/text_field/voices_text_field.dart
- catalyst_voices/pubspec.yaml
- catalyst_voices/test/widgets/text_field/voices_text_field_test.dart
- catalyst_voices/uikit_example/lib/examples/voices_text_field_example.dart
- catalyst_voices/uikit_example/lib/examples_list.dart
Adds custom Text fields.
Closes #657 
https://github.com/user-attachments/assets/0019b801-8c2f-42d9-99a5-ff0dc6a3107d
> feat: uikit text fields

- catalyst_voices/nginx.conf
We're deploying `m4` related pages to https://voices.projectcatalyst.io/ as we're waiting for **dev** env. This change should let us see those pages.
Example pages that we want to be able to see
- /m4/treasury
- /m4/discovery
- /m4/workspace
- /m4/voting
- /m4/funded_projects 
As per spaces routing [here](https://github.com/input-output-hk/catalyst-voices/blob/main/catalyst_voices/lib/routes/routing/spaces_route.dart#L15)
Part of #762 
Relates to #765
> feat: allow m4 subpages in voices

- catalyst_voices/lib/widgets/avatars/voices_avatar.dart
Fixes avatar letter center 
Before:
After:
> fix(cat-voices): center avatar letter

- catalyst_voices/lib/widgets/avatars/voices_avatar.dart
- catalyst_voices/lib/widgets/modals/voices_alert_dialog.dart
- catalyst_voices/lib/widgets/modals/voices_desktop_dialog.dart
- catalyst_voices/lib/widgets/modals/voices_dialog.dart
- catalyst_voices/lib/widgets/modals/voices_info_dialog.dart
- catalyst_voices/lib/widgets/widgets.dart
- catalyst_voices/packages/catalyst_voices_brands/lib/src/themes/catalyst.dart
- catalyst_voices/test/widgets/avatars/voices_avatar_test.dart
- catalyst_voices/uikit_example/lib/examples/voices_avatar_example.dart
- catalyst_voices/uikit_example/lib/examples/voices_modals_example.dart
Adds a generic alert dialog.
Closes #814
> feat(cat-voices): alert dialog

- catalyst_voices_packages/catalyst_cardano/catalyst_cardano/README.md
- catalyst_voices_packages/catalyst_cardano_serialization/README.md
Fixes samples in README.md files after recent refactors.
> fix(dart/catalyst_cardano_serialization): fix samples in readme

- catalyst_voices/lib/pages/account/creation/task_picture.dart
Fixes scaling problem of task **TaskPicture**
Part of #816 
Part of #818 
https://github.com/user-attachments/assets/b7943ef2-1b84-42d0-9ee7-4b8e88acc281
> fix(cat-voices): task picture scaling

- catalyst_voices/lib/pages/registration/wallet_link/stage/wallet_details_panel.dart
- catalyst_voices/lib/pages/registration/wallet_link/wallet_link_panel.dart
- catalyst_voices/packages/catalyst_voices_blocs/lib/src/registration/cubits/wallet_link_cubit.dart
- catalyst_voices/packages/catalyst_voices_blocs/lib/src/registration/wallet_link_state_data.dart
- catalyst_voices/packages/catalyst_voices_localization/lib/generated/catalyst_voices_localizations.dart
- catalyst_voices/packages/catalyst_voices_localization/lib/generated/catalyst_voices_localizations_en.dart
- catalyst_voices/packages/catalyst_voices_localization/lib/generated/catalyst_voices_localizations_es.dart
- catalyst_voices/packages/catalyst_voices_localization/lib/l10n/intl_en.arb
- catalyst_voices/packages/catalyst_voices_models/lib/src/wallet/cardano_wallet_details.dart
Adds "Not enough balance" state to wallet details screen during registration.
Refers #818
> feat(cat-voices): wallet link details empty balance

- catalyst_voices/lib/pages/registration/create_keychain/create_keychain_panel.dart
- catalyst_voices/lib/pages/registration/create_keychain/stage/check_seed_phrase_instructions_panel.dart
- catalyst_voices/lib/pages/registration/registration_info_panel.dart
- catalyst_voices/packages/catalyst_voices_localization/lib/generated/catalyst_voices_localizations.dart
- catalyst_voices/packages/catalyst_voices_localization/lib/generated/catalyst_voices_localizations_en.dart
- catalyst_voices/packages/catalyst_voices_localization/lib/generated/catalyst_voices_localizations_es.dart
- catalyst_voices/packages/catalyst_voices_localization/lib/l10n/intl_en.arb
This PR adds simple text panel for check seed phrase instructions 
Part of #816
> feat(cat-voices): check seed phrase instructions stage

- catalyst_voices/lib/pages/registration/create_keychain/create_keychain_panel.dart
- catalyst_voices/lib/pages/registration/create_keychain/stage/seed_phrase_check_panel.dart
- catalyst_voices/lib/pages/registration/create_keychain/stage/seed_phrase_check_result_panel.dart
- catalyst_voices/lib/pages/registration/create_keychain/stage/seed_phrase_panel.dart
- catalyst_voices/lib/pages/registration/create_keychain/stage/stages.dart
- catalyst_voices/lib/pages/registration/next_step.dart
- catalyst_voices/lib/pages/registration/registration_info_panel.dart
- catalyst_voices/lib/widgets/common/infrastructure/voices_loadable.dart
- catalyst_voices/lib/widgets/seed_phrase/seed_phrases_completer.dart
- catalyst_voices/lib/widgets/seed_phrase/seed_phrases_picker.dart
- catalyst_voices/lib/widgets/seed_phrase/seed_phrases_sequencer.dart
- catalyst_voices/lib/widgets/seed_phrase/seed_phrases_viewer.dart
- catalyst_voices/lib/widgets/widgets.dart
- catalyst_voices/packages/catalyst_voices_blocs/lib/src/registration/cubits/keychain_creation_cubit.dart
- catalyst_voices/packages/catalyst_voices_blocs/lib/src/registration/registration_cubit.dart
- catalyst_voices/packages/catalyst_voices_blocs/lib/src/registration/seed_phrase_state.dart
- catalyst_voices/packages/catalyst_voices_localization/lib/generated/catalyst_voices_localizations.dart
- catalyst_voices/packages/catalyst_voices_localization/lib/generated/catalyst_voices_localizations_en.dart
- catalyst_voices/packages/catalyst_voices_localization/lib/generated/catalyst_voices_localizations_es.dart
- catalyst_voices/packages/catalyst_voices_localization/lib/l10n/intl_en.arb
- catalyst_voices/packages/catalyst_voices_models/lib/src/seed_phrase.dart
- catalyst_voices/test/widgets/seed_phrase/seed_phrases_sequencer_test.dart
- catalyst_voices/uikit_example/lib/examples/voices_seed_phrase_example.dart
This PR adds checking seed phrase order by user as well as result panel
Part of #816
> feat(cat-voices): check seed phrase and result panel

- catalyst_voices/lib/pages/registration/registration_dialog.dart
Makes `RegistrationDialog` not dismissible when clicking outside. Now user have to make conscious decision by clicking "X" button to exit.
> feat(cat-voices): not dismissible registration dialog

- catalyst_voices/lib/pages/registration/create_keychain/create_keychain_panel.dart
- catalyst_voices/lib/pages/registration/create_keychain/stage/instructions_panel.dart
- catalyst_voices/lib/pages/registration/create_keychain/stage/seed_phrase_check_instructions_panel.dart
- catalyst_voices/lib/pages/registration/create_keychain/stage/seed_phrase_check_panel.dart
- catalyst_voices/lib/pages/registration/create_keychain/stage/seed_phrase_check_result_panel.dart
- catalyst_voices/lib/pages/registration/create_keychain/stage/unlock_password_instructions_panel.dart
- catalyst_voices/lib/pages/registration/pictures/password_picture.dart
- catalyst_voices/lib/pages/registration/registration_info_panel.dart
- catalyst_voices/packages/catalyst_voices_localization/lib/generated/catalyst_voices_localizations.dart
- catalyst_voices/packages/catalyst_voices_localization/lib/generated/catalyst_voices_localizations_en.dart
- catalyst_voices/packages/catalyst_voices_localization/lib/generated/catalyst_voices_localizations_es.dart
- catalyst_voices/packages/catalyst_voices_localization/lib/l10n/intl_en.arb
- Adds Unlock password instructions panel
- Allows user see result seed phrase stage when incorrect order
Part of #816
> feat(cat-voices): seed phrase error result and unlock password instructions

- catalyst_voices/lib/pages/account/account_page.dart
- catalyst_voices/lib/pages/registration/wallet_link/stage/rbac_transaction_panel.dart
- catalyst_voices/lib/pages/registration/wallet_link/stage/wallet_details_panel.dart
- catalyst_voices/lib/pages/registration/wallet_link/wallet_link_panel.dart
- catalyst_voices/lib/widgets/list/bullet_list.dart
- catalyst_voices/lib/widgets/widgets.dart
- catalyst_voices/packages/catalyst_voices_blocs/lib/src/registration/registration_cubit.dart
- catalyst_voices/packages/catalyst_voices_localization/lib/generated/catalyst_voices_localizations.dart
- catalyst_voices/packages/catalyst_voices_localization/lib/generated/catalyst_voices_localizations_en.dart
- catalyst_voices/packages/catalyst_voices_localization/lib/generated/catalyst_voices_localizations_es.dart
- catalyst_voices/packages/catalyst_voices_localization/lib/l10n/intl_en.arb
Adds a transaction summary for registration.
Refers #818
> feat(cat-voices): registration transaction summary

- catalyst_voices/lib/widgets/indicators/voices_no_internet_connection_banner.dart
- catalyst_voices/lib/widgets/indicators/voices_status_indicator.dart
- catalyst_voices/packages/catalyst_voices_assets/assets/colors/colors.xml
- catalyst_voices/packages/catalyst_voices_assets/lib/generated/colors.gen.dart
- catalyst_voices/packages/catalyst_voices_brands/lib/src/theme_extensions/voices_color_scheme.dart
- catalyst_voices/packages/catalyst_voices_brands/lib/src/themes/catalyst.dart
Aligns colors with designs.
Closes #938
Light theme:
Dark theme:
> fix(cat-voices): align colors with designs

- catalyst_voices/lib/pages/registration/finish_account/finish_account_creation_panel.dart
- catalyst_voices/packages/catalyst_voices_assets/example/web/index.html
- catalyst_voices/uikit_example/web/index.html
- catalyst_voices/web/index.html
- catalyst_voices_packages/catalyst_cardano/catalyst_cardano/example/web/index.html
- utilities/catalyst_voices_remote_widgets/example/web/index.html
- utilities/poc_local_storage/web/index.html
Migrates deprecated `migrate apple-mobile-web-app-capable` meta tag to `mobile-web-app-capable`.
- `https://github.com/flutter/flutter/pull/154964`
> fix(cat-voices): migrate apple-mobile-web-app-capable to mobile-web-app-capable

- catalyst_voices/macos/Flutter/GeneratedPluginRegistrant.swift
- catalyst_voices/pubspec.yaml
- catalyst_voices/uikit_example/pubspec.yaml
- catalyst_voices/uikit_example/web/index.html
- catalyst_voices/web/index.html
- melos.yaml
There was an issue with  flutter_inappwebview's web_support.js not found 
Newer version of `flutter_quill_extensions` doesn't use `flutter_inappwebview` and we explicitly added reference to `web_support.js` to index.html before, so now it needed to be removed.
Also I upgraded here `flutter_quill_extensions ` explicitly and cleaned related files.
> fix(cat-voices): flutter_inappwebview's web_support.js not found error

- catalyst_voices/test/widgets/indicators/voices_status_indicator_test.dart
Fixes unit tests for VoicesStatusIndicator
Refers #959
> fix(cat-voices): unit tests for status indicator

- catalyst_voices/packages/catalyst_voices_models/pubspec.yaml
- catalyst_voices/packages/catalyst_voices_models/test/auth/password_strength_test.dart
- catalyst_voices/packages/catalyst_voices_models/test/optional_test.dart
- catalyst_voices/packages/catalyst_voices_models/test/seed_phrase_test.dart
Use `test` package in `catalyst_voices_models` package as it does not depend on flutter.
> fix(cat-voices): use dart test in models package

- .github/workflows/generate-allure-report.yml
- .github/workflows/nightly-ci.yml
Adding a slack notification for nightly CI run.
> e.g., Resolves #751 
Added a step in Github Action for Nightly CI to send a link and summary of tests to Slack channel.
There are no breaking changes.
no related PR
> e.g., #1, #1
> test(cat-voices): add allure report to slack

- catalyst-gateway/Earthfile
Set the container entrypoint to cat-gateway binary.
#50 
Remove entry.sh from the container and set the entrypoint as the cat-gateway binary.
> Set cat-gateway as the container entrypoint

- catalyst_voices/lib/common/error_handler.dart
- catalyst_voices/lib/pages/registration/create_keychain/stage/unlock_password_panel.dart
- catalyst_voices/lib/pages/registration/registration_dialog.dart
- catalyst_voices/packages/catalyst_voices_blocs/lib/src/bloc_error_emitter_mixin.dart
- catalyst_voices/packages/catalyst_voices_blocs/lib/src/catalyst_voices_blocs.dart
- catalyst_voices/packages/catalyst_voices_blocs/lib/src/registration/cubits/keychain_creation_cubit.dart
- catalyst_voices/packages/catalyst_voices_blocs/lib/src/registration/cubits/recover_cubit.dart
- catalyst_voices/packages/catalyst_voices_blocs/lib/src/registration/cubits/wallet_link_cubit.dart
- catalyst_voices/packages/catalyst_voices_blocs/lib/src/registration/registration_cubit.dart
- catalyst_voices/packages/catalyst_voices_localization/lib/generated/catalyst_voices_localizations.dart
- catalyst_voices/packages/catalyst_voices_localization/lib/generated/catalyst_voices_localizations_en.dart
- catalyst_voices/packages/catalyst_voices_localization/lib/generated/catalyst_voices_localizations_es.dart
- catalyst_voices/packages/catalyst_voices_localization/lib/l10n/intl_en.arb
- catalyst_voices/packages/catalyst_voices_services/lib/src/registration/registration_service.dart
- catalyst_voices/packages/catalyst_voices_view_models/lib/src/registration/exception/localized_registration_exception.dart
- Adds basic implementation of streaming errors from bloc/cubit to root widget
- Mixing with snackbar handling of `LocalizedException`s
> feat(cat-voices): blocs errors stream and basic handling

- catalyst_voices/lib/pages/registration/bloc_unlock_password_builder.dart
- catalyst_voices/lib/pages/registration/create_keychain/stage/unlock_password_panel.dart
- catalyst_voices/lib/pages/registration/recover/recover_seed_phrase_panel.dart
- catalyst_voices/lib/pages/registration/recover/seed_phrase/unlock_password_instructions_panel.dart
- catalyst_voices/lib/pages/registration/recover/seed_phrase/unlock_password_panel.dart
- catalyst_voices/lib/pages/registration/registration_info_panel.dart
- catalyst_voices/lib/pages/registration/widgets/unlock_password_form.dart
- catalyst_voices/packages/catalyst_voices_blocs/lib/src/registration/cubits/keychain_creation_cubit.dart
- catalyst_voices/packages/catalyst_voices_blocs/lib/src/registration/cubits/recover_cubit.dart
- catalyst_voices/packages/catalyst_voices_blocs/lib/src/registration/cubits/unlock_password_manager.dart
- catalyst_voices/packages/catalyst_voices_blocs/lib/src/registration/state_data/recover_state_data.dart
- catalyst_voices/packages/catalyst_voices_blocs/lib/src/registration/state_data/unlock_password_state.dart
- catalyst_voices/packages/catalyst_voices_localization/lib/generated/catalyst_voices_localizations.dart
- catalyst_voices/packages/catalyst_voices_localization/lib/generated/catalyst_voices_localizations_en.dart
- catalyst_voices/packages/catalyst_voices_localization/lib/generated/catalyst_voices_localizations_es.dart
- catalyst_voices/packages/catalyst_voices_localization/lib/l10n/intl_en.arb
- catalyst_voices/packages/catalyst_voices_view_models/lib/src/authentication/authentication.dart
- catalyst_voices/packages/catalyst_voices_view_models/lib/src/authentication/unlock_password.dart
- Adds recovery unlock password steps 
- Extracts common password widgets
- Closes #955 
- Closes #956
> feat(cat-voices): restore unlock password

- docs/src/architecture/08_concepts/voting_transaction/crypto.md
- docs/src/architecture/08_concepts/voting_transaction/transaction.md
Updated the voting protocol with the jormungandr tx specifications. 
Provided missing parts.
https://github.com/input-output-hk/catalyst-libs/pull/58
> fix(docs): Update voting protocol definition and the jormnugandr tx spec

- catalyst_voices/packages/catalyst_voices_localization/l10n.yaml
- catalyst_voices/packages/catalyst_voices_localization/lib/generated/catalyst_voices_localizations.dart
- catalyst_voices/packages/catalyst_voices_localization/lib/generated/catalyst_voices_localizations_en.dart
- catalyst_voices/packages/catalyst_voices_localization/lib/generated/catalyst_voices_localizations_es.dart
- catalyst_voices/packages/catalyst_voices_localization/lib/l10n/intl_en.arb
The special character `'` needs to be escaped in arb files by prepending another `'` in front of it, otherwise it's interpreted as a start of escaping sequence. Since this would require a lot of attention while adding localizations lets disable escaping but allow relax-syntax which will show special characters as they are if they are not formed properly.
I.e. `{name}` would be considered a localization with name variable, `{name` would just simply display as `{name`.
- docs with available `l10n.yaml` options: https://docs.flutter.dev/ui/accessibility-and-internationalization/internationalization#configuring-the-l10n-yaml-file
> fix(cat-voices): escape special characters in arb

- .github/workflows/ci.yml
- .github/workflows/generate-allure-report.yml
Add running allure report flow after forge ci job
Implements #974 
Add running allure report flow after forge ci job
-
-
Part 1 #1006
> refactor(general): add running allure report flow after forge ci job part 2

- catalyst_voices/lib/routes/guards/composite_route_guard_mixin.dart
- catalyst_voices/lib/routes/guards/session_unlocked_guard.dart
- catalyst_voices/lib/routes/guards/unlocked_keychain_guard_mixin.dart
- catalyst_voices/lib/routes/routing/account_route.dart
Adds route guard for account page to prevent by-passing keychain lock by entering the account page url directly in the browser.
Closes #1045
> feat(cat-voices): add route guard for account page

- catalyst_voices/apps/voices/lib/pages/account/delete_keychain_dialog.dart
- catalyst_voices/apps/voices/lib/pages/login/login_email_text_filed.dart
- catalyst_voices/apps/voices/lib/pages/voting/voting_page.dart
- catalyst_voices/apps/voices/lib/widgets/text_field/voices_email_text_field.dart
- catalyst_voices/apps/voices/lib/widgets/text_field/voices_text_field.dart
- catalyst_voices/apps/voices/test/widgets/text_field/voices_text_field_test.dart
- catalyst_voices/utilities/uikit_example/lib/examples/voices_text_field_example.dart
Making it required but nullable because default behaviour is to make some action when user taps enter. Focus next field or do smth else.
> feat(cat-voices): text field required onFieldSubmitted

- catalyst_voices/apps/voices/lib/pages/registration/recover/seed_phrase/account_details_panel.dart
- catalyst_voices/packages/internal/catalyst_voices_blocs/lib/src/registration/cubits/recover_cubit.dart
- catalyst_voices/packages/internal/catalyst_voices_blocs/lib/src/session/session_cubit.dart
- catalyst_voices/packages/internal/catalyst_voices_blocs/test/session/session_cubit_test.dart
- catalyst_voices/packages/internal/catalyst_voices_localization/lib/generated/catalyst_voices_localizations.dart
- catalyst_voices/packages/internal/catalyst_voices_localization/lib/generated/catalyst_voices_localizations_en.dart
- catalyst_voices/packages/internal/catalyst_voices_localization/lib/generated/catalyst_voices_localizations_es.dart
- catalyst_voices/packages/internal/catalyst_voices_localization/lib/l10n/intl_en.arb
- catalyst_voices/packages/internal/catalyst_voices_services/lib/src/user/user_service.dart
- catalyst_voices/packages/internal/catalyst_voices_services/test/src/user/user_service_test.dart
This PR adds recover different keychain option to recovery flow
Resolves #1092
> feat(cat-voices): recover different keychain

- .config/dictionaries/project.dic
- .earthlyignore
- catalyst-gateway/.earthlyignore
- catalyst_voices/.earthlyignore
The PR adds `.earthlyignore` files next to relevant `Earthfile` so that local files created during development that constantly change are not copied into the earthly build context because it breaks caching.
The `**/Earthfile` exclusion has been removed because it might be necessary to check spelling in this file so it should not be skipped.
> fix(general): .earthlyignore to avoid copying irrelevant files into earthly context

- catalyst_voices/apps/voices/integration_test/Earthfile
Disables flaky integration tests until `flutter drive` is fixed to not block pending frontend PRs.
```
https://github.com/flutter/flutter/issues/159037
```
> fix: disable flaky integration tests

- catalyst_voices/utilities/uikit_example/Earthfile
Fixes UIKit deployment:
https://github.com/input-output-hk/catalyst-voices/actions/runs/11891897467
The target hasn't been updated when generated code has been removed from the repository and builds on top of catalyst voices target which doesn't have generated code.
> fix(cat-voices): uikit deployment

- .github/ISSUE_TEMPLATE/test_plan.yml
> fix: testplan template

- catalyst_voices/apps/voices/lib/widgets/menu/voices_menu.dart
- catalyst_voices/apps/voices/lib/widgets/menu/voices_modal_menu.dart
- catalyst_voices/apps/voices/lib/widgets/modals/campaign/campaign_categories_tile.dart
- catalyst_voices/apps/voices/test/widgets/menu/voices_menu_test.dart
- catalyst_voices/packages/internal/catalyst_voices_localization/lib/l10n/intl_en.arb
- catalyst_voices/packages/internal/catalyst_voices_services/lib/src/keychain/vault_keychain.dart
- catalyst_voices/packages/internal/catalyst_voices_services/lib/src/storage/vault/secure_storage_vault.dart
- catalyst_voices/packages/internal/catalyst_voices_services/lib/src/storage/vault/vault.dart
- catalyst_voices/packages/internal/catalyst_voices_services/test/src/keychain/vault_keychain_provider_test.dart
- catalyst_voices/packages/internal/catalyst_voices_services/test/src/keychain/vault_keychain_test.dart
- catalyst_voices/packages/internal/catalyst_voices_services/test/src/user/user_service_test.dart
- catalyst_voices/packages/internal/catalyst_voices_view_models/lib/src/campaign/campaign_category.dart
- catalyst_voices/packages/internal/catalyst_voices_view_models/lib/src/campaign/campaign_section.dart
- catalyst_voices/packages/internal/catalyst_voices_view_models/lib/src/catalyst_voices_view_models.dart
- catalyst_voices/packages/internal/catalyst_voices_view_models/lib/src/menu/menu_item.dart
- catalyst_voices/packages/internal/catalyst_voices_view_models/lib/src/menu/popup_menu_item.dart
- catalyst_voices/utilities/uikit_example/lib/examples/voices_menu_example.dart
This PR adds new widget component
- Interface `MenuItem` and `PopupMenuItem` so other models can be used as items for models widgets.
- Very probably `CampaignSection` should have body as `RichText` body (Markdown?) but atm. using simple String
Resolves #1185 
https://github.com/user-attachments/assets/d0e7ff89-cfb5-4832-8c28-1d1268ce8eee
> feat(cat-voices): campaign categories

- catalyst_voices/apps/voices/lib/widgets/empty_state/empty_state.dart
- catalyst_voices/apps/voices/lib/widgets/images/voices_image_scheme.dart
- catalyst_voices/apps/voices/test/widgets/empty_state/empty_state_test.dart
I transform NoProposals widget to EmptyState to more usability.
> refactor(cat-voices): Changing NoProposals widget to EmptyState

- catalyst_voices/apps/voices/pubspec.yaml
- catalyst_voices/melos.yaml
- catalyst_voices/packages/internal/catalyst_voices_blocs/pubspec.yaml
- catalyst_voices/packages/internal/catalyst_voices_models/pubspec.yaml
- catalyst_voices/packages/internal/catalyst_voices_services/lib/src/keychain/vault_keychain.dart
- catalyst_voices/packages/internal/catalyst_voices_services/lib/src/storage/vault/secure_storage_vault.dart
- catalyst_voices/packages/internal/catalyst_voices_services/lib/src/storage/vault/vault.dart
- catalyst_voices/packages/internal/catalyst_voices_services/pubspec.yaml
- catalyst_voices/packages/internal/catalyst_voices_services/test/src/keychain/vault_keychain_provider_test.dart
- catalyst_voices/packages/internal/catalyst_voices_services/test/src/keychain/vault_keychain_test.dart
- catalyst_voices/packages/internal/catalyst_voices_services/test/src/user/user_service_test.dart
- catalyst_voices/packages/internal/catalyst_voices_view_models/pubspec.yaml
- catalyst_voices/packages/libs/catalyst_cardano/catalyst_cardano/example/pubspec.yaml
- catalyst_voices/packages/libs/catalyst_cardano/catalyst_cardano_platform_interface/pubspec.yaml
- catalyst_voices/packages/libs/catalyst_cardano_serialization/pubspec.yaml
- catalyst_voices/packages/libs/catalyst_compression/catalyst_compression_platform_interface/pubspec.yaml
- catalyst_voices/packages/libs/catalyst_key_derivation/pubspec.yaml
Fixes broken lint in Catalyst Voices. This has been already [fixed in MVE3](https://github.com/input-output-hk/catalyst-voices/pull/1251/files#diff-c31fec6393780fb65b13601aa23ce31c94b845b8b04013ddb182aca8655edd54L251) but we need to fix in `main` too before we can merge `main` branch into `mve3` due to required checks (like static-analysis).
> fix(cat-voices): equatable lint issue fix

- catalyst-gateway/bin/Cargo.toml
- Updated cat-gateway to use `cardano-chain-follower` v0.0.5
Closes #1296
> chore(cat-gateway): bump `cardano-chain-follower` version to v0.0.5

- catalyst_voices/packages/internal/catalyst_voices_models/lib/src/user/account_role.dart
- catalyst_voices/packages/internal/catalyst_voices_services/lib/src/crypto/key_derivation.dart
- catalyst_voices/packages/internal/catalyst_voices_services/lib/src/registration/registration_transaction_builder.dart
- catalyst_voices/packages/internal/catalyst_voices_services/test/src/crypto/key_derivation_test.dart
Updates key derivation path based on new specification: https://github.com/input-output-hk/catalyst-voices/pull/1300
> fix(cat-voices): update key derivation path

- .config/dictionaries/project.dic
- catalyst_voices/apps/voices/lib/pages/campaign/admin_tools/campaign_admin_tools_dialog.dart
- catalyst_voices/apps/voices/lib/pages/campaign/admin_tools/campaign_admin_tools_events.dart
- catalyst_voices/apps/voices/lib/pages/campaign/admin_tools/campaign_admin_tools_views.dart
- catalyst_voices/apps/voices/lib/pages/spaces/spaces_shell_page.dart
- catalyst_voices/apps/voices/lib/widgets/cards/campaign_preview_card.dart
- catalyst_voices/apps/voices/test/widgets/cards/campaign_preview_card_test.dart
- catalyst_voices/packages/internal/catalyst_voices_localization/lib/l10n/intl_en.arb
- catalyst_voices/packages/internal/catalyst_voices_models/lib/src/campaign/campaign_status.dart
- catalyst_voices/packages/internal/catalyst_voices_models/lib/src/catalyst_voices_models.dart
- catalyst_voices/packages/internal/catalyst_voices_view_models/lib/src/campaign/admin/campaign_preview_info.dart
- catalyst_voices/packages/internal/catalyst_voices_view_models/lib/src/campaign/admin/campaign_status_info.dart
- catalyst_voices/packages/internal/catalyst_voices_view_models/lib/src/catalyst_voices_view_models.dart
Adds the first iteration of campaign admin tools which allows:
- switching between spaces
- switching between session states (actor, visitor, guest)
- switching between different campaign stages (to be done in the next PR)
The admin tools dialog can be shown/closed with ctrl+shift+A keyboard combination.
Refers #1113
https://github.com/user-attachments/assets/ae6e7634-9ddd-4c69-981a-cab905d329ac
> feat(cat-voices): admin preview tools

- catalyst-gateway/bin/src/db/index/block/mod.rs
- catalyst-gateway/bin/src/db/index/block/rbac509/insert_chain_root_for_stake_address.rs
- catalyst-gateway/bin/src/db/index/queries/mod.rs
> fix: naming mismatch

- catalyst-gateway/bin/src/db/event/mod.rs
- catalyst-gateway/bin/src/settings/mod.rs
- Fixed `DATABASE_SCHEMA_VERSION` from `9` to `2`.
- Removed unused `event_db_url` cat-gateway cli `run` command argument
> fix(cat-gateway): Fix `DATABASE_SCHEMA_VERSION`, remove unused `event_db_url` cli arg

- catalyst_voices/melos.yaml
- catalyst_voices/packages/libs/catalyst_cardano_serialization/lib/src/rbac/auth_token.dart
- catalyst_voices/packages/libs/catalyst_cardano_serialization/lib/src/utils/cbor.dart
- catalyst_voices/packages/libs/catalyst_cardano_serialization/lib/src/utils/uuid.dart
- catalyst_voices/packages/libs/catalyst_cardano_serialization/pubspec.yaml
- catalyst_voices/packages/libs/catalyst_cardano_serialization/test/rbac/auth_token_test.dart
Replaces ulid by UUID v7 in auth token.
token cbor: 
```
50431d7b744dcc4ac4359b7ee7ffa7be33d8255001856aa0c8007a1d82b02c77a8db72525840604b50613e4ed56d94ec1038bb4fce75b616fc3249134c4cb73407281c7396c608d46990981fccc181211858387926acba5e99036d74e5dc66328a5b0e74b30d
```
uuid cbor:
```
37(h'01856AA0C8007A1D82B02C77A8DB7252')
```
> feat(dart/catalyst_cardano_serialization): replace ulid by UUID in auth token

- catalyst_voices/apps/voices/lib/app/view/app_content.dart
When app unlock state is resumed there may be no scaffold available yet. This PR is adding one on top of the app.
> fix(cat-voices): snackbar no scaffold error

- catalyst_voices/apps/voices/integration_test/app_test.dart
- catalyst_voices/apps/voices/integration_test/pageobject/spaces_drawer_page.dart
> test(cat-voices): integration tests cleanup

- .config/dictionaries/project.dic
- catalyst_voices/apps/voices/integration_test/onboarding_test.dart
- catalyst_voices/apps/voices/integration_test/pageobject/app_bar_page.dart
- catalyst_voices/apps/voices/integration_test/pageobject/common_page.dart
- catalyst_voices/apps/voices/integration_test/pageobject/onboarding_page.dart
- catalyst_voices/apps/voices/integration_test/types/registration_state.dart
- catalyst_voices/apps/voices/integration_test/utils/translations_utils.dart
- catalyst_voices/apps/voices/lib/pages/registration/get_started/get_started_panel.dart
- catalyst_voices/apps/voices/lib/pages/registration/registration_details_panel.dart
- catalyst_voices/apps/voices/lib/pages/registration/registration_info_panel.dart
- catalyst_voices/apps/voices/lib/pages/registration/widgets/information_panel.dart
- catalyst_voices/apps/voices/lib/pages/registration/widgets/registration_stage_message.dart
- catalyst_voices/apps/voices/lib/widgets/buttons/voices_buttons.dart
- catalyst_voices/apps/voices/lib/widgets/common/affix_decorator.dart
- catalyst_voices/apps/voices/lib/widgets/modals/voices_desktop_dialog.dart
Integration tests start automating onboarding
Implements #1429 
Integration tests start automating onboarding
-
> e.g., #1, #1
> test(cat-voices): integration tests start automating onboarding

- catalyst_voices/apps/voices/integration_test/onboarding_test.dart
- catalyst_voices/apps/voices/integration_test/pageobject/app_bar_page.dart
- catalyst_voices/apps/voices/integration_test/pageobject/onboarding_page.dart
- catalyst_voices/apps/voices/lib/pages/registration/widgets/information_panel.dart
- catalyst_voices/apps/voices/lib/widgets/common/affix_decorator.dart
- Fix the formatting of integration test code
> fix(cat-voices): code formatting

- catalyst_voices/packages/internal/catalyst_voices_models/lib/src/document/document_schema.dart
- catalyst_voices/packages/internal/catalyst_voices_repositories/lib/src/dto/document/schema/document_schema_property_dto.dart
- catalyst_voices/packages/internal/catalyst_voices_repositories/lib/src/dto/document/schema/document_schema_section_dto.dart
- catalyst_voices/packages/internal/catalyst_voices_repositories/lib/src/dto/document/schema/document_schema_segment_dto.dart
- catalyst_voices/packages/internal/catalyst_voices_repositories/lib/src/utils/document_schema_dto_converter.dart
- Ignore conditional logic, skipped for F14.
- Allow `properties` to be nullable.
- Make `title` required, `description` optional.
Refers #1265
> refactor(cat-voices): simplify document parsing

- catalyst_voices/packages/internal/catalyst_voices_models/lib/src/document/document_schema.dart
- catalyst_voices/packages/internal/catalyst_voices_repositories/lib/src/dto/document/schema/document_schema_property_dto.dart
- catalyst_voices/packages/internal/catalyst_voices_repositories/lib/src/dto/document/schema/document_schema_section_dto.dart
- Fixes tests by allowing the title to be optional on section/property level in a document.
> fix(cat-voices): allow optional title in document properties/sections

- catalyst_voices/apps/voices/lib/widgets/document_builder/agreement_confirmation_widget.dart
- catalyst_voices/apps/voices/lib/widgets/rich_text/placeholder_rich_text.dart
- catalyst_voices/apps/voices/lib/widgets/text_field/token_field.dart
- catalyst_voices/apps/voices/lib/widgets/widgets.dart
- catalyst_voices/packages/internal/catalyst_voices_localization/lib/l10n/intl_en.arb
- catalyst_voices/packages/internal/catalyst_voices_models/lib/src/money/currency.dart
- Adds new general widget `PlaceholderRichText` which can replace string placeholder values
- `TokenField` helper now handles nullable range
> feat(cat-voices): PlaceholderRichText and TokenValue helper handles nullable range

- .markdownlint-cli2.jsonc
- catalyst_voices/CHANGELOG.md
- catalyst_voices/apps/voices/pubspec.yaml
- catalyst_voices/packages/internal/catalyst_voices_blocs/pubspec.yaml
- catalyst_voices/packages/internal/catalyst_voices_models/pubspec.yaml
- catalyst_voices/packages/internal/catalyst_voices_repositories/pubspec.yaml
- catalyst_voices/packages/internal/catalyst_voices_services/pubspec.yaml
- catalyst_voices/packages/internal/catalyst_voices_shared/pubspec.yaml
- catalyst_voices/packages/internal/catalyst_voices_view_models/pubspec.yaml
- catalyst_voices/packages/libs/catalyst_cardano/catalyst_cardano/CHANGELOG.md
- catalyst_voices/packages/libs/catalyst_cardano/catalyst_cardano/example/pubspec.yaml
- catalyst_voices/packages/libs/catalyst_cardano/catalyst_cardano/pubspec.yaml
- catalyst_voices/packages/libs/catalyst_cardano/catalyst_cardano_platform_interface/CHANGELOG.md
- catalyst_voices/packages/libs/catalyst_cardano/catalyst_cardano_platform_interface/pubspec.yaml
- catalyst_voices/packages/libs/catalyst_cardano/catalyst_cardano_web/CHANGELOG.md
- catalyst_voices/packages/libs/catalyst_cardano/catalyst_cardano_web/pubspec.yaml
- catalyst_voices/packages/libs/catalyst_cardano_serialization/CHANGELOG.md
- catalyst_voices/packages/libs/catalyst_cardano_serialization/pubspec.yaml
- catalyst_voices/packages/libs/catalyst_key_derivation/CHANGELOG.md
- catalyst_voices/packages/libs/catalyst_key_derivation/pubspec.yaml
- catalyst_voices/utilities/uikit_example/pubspec.yaml
- catalyst_cardano@0.4.0+3
- catalyst_key_derivation@0.1.2
- catalyst_cardano_serialization@0.5.0+3
- catalyst_cardano_web@0.4.0+3
- catalyst_cardano_platform_interface@0.4.0+3
Release dart/flutter packages to pub.dev. The changelogs are automatically generated by melos from commit history.
#1471
> chore(flutter): publish packages

- catalyst_voices/packages/libs/catalyst_cardano/catalyst_cardano/wallet-automation/playwright.config.ts
- catalyst_voices/packages/libs/catalyst_cardano/catalyst_cardano/wallet-automation/tests/wallets.spec.ts
- catalyst_voices/packages/libs/catalyst_cardano/catalyst_cardano/wallet-automation/utils/wallets/laceUtils.ts
- catalyst_voices/packages/libs/catalyst_cardano/catalyst_cardano/wallet-automation/utils/wallets/walletUtils.ts
Re-enabled Lace tests in wallet automation
Resolves #1602 
Few minor changes were needed to make tests a little bit more stable.
> test(cat-voices): add automation for lace

- docs/src/architecture/08_concepts/domain-models/index.md
Fix the following CI `WARNING` failure
```
./docs+docs | WARNING -  Doc file 'architecture/08_concepts/domain-models/index.md' contains a link 'src/architecture/08_concepts/domain-models/diagrams/entity_fund14.d2', but the target 'architecture/08_concepts/domain-models/src/architecture/08_concepts/domain-models/diagrams/entity_fund14.d2' is not found among documentation files.
```
> fix(docs): Fix invalid md link

- catalyst_voices/apps/voices/lib/widgets/text_field/voices_https_text_field.dart
- catalyst_voices/apps/voices/lib/widgets/text_field/voices_text_field.dart
This just changes mouse to click if https textfield is not in edit mode for better visual that its clickable.
> chore(cat-voices): Making mouse on https text field as a click

- catalyst-gateway/bin/src/service/api/health/mod.rs
- catalyst-gateway/bin/src/service/api/health/ready_get.rs
rm auth for k8s health checks and temporarily rm schema version check until we fix it.
> chore(cat-gateway): rm auth k8s health check

- .github/workflows/nightly-ci.yml
Remove integration tests from nightly run.
Tests are too flaky for CI in a current state, they can be run locally fairly quickly.
Plan is to come back to this when related flutter issue is released officially by flutter, issue [here](https://github.com/flutter/flutter/pull/159039)
> e.g., #1, #1
> test(cat-voices): Remove integration tests from nightly run

- catalyst-gateway/Cargo.toml
Removed unneeded patch of `orx-pseudo-default` as https://github.com/orxfun/orx-pseudo-default/issues/11 resolved
> feat(cat-gateway): Remove unneeded patch of `orx-pseudo-default`

- catalyst_voices/apps/voices/lib/widgets/document_builder/multiline_text_entry_markdown_widget.dart
- catalyst_voices/apps/voices/lib/widgets/rich_text/voices_rich_text.dart
Recognizes common markdown patterns like `**bold**` which gets translated on the fly to **bold**.
Supported patterns:
- `- ` (dash and space) - unordered list
- `1. ` (number and dot) - ordered list
- `**text**` - bold
- `*text*` - italic
- `# ` - (hash and space) - header
Additional changes:
- remove indents, markdown doesn't support them
- make sure to don't update the `VoicesRichText` unnecessarily, each time it reloads the quill editor cleanups blank lines which might be conflicting with the user wanting to insert a blank line and then writing something below it
Closes #1743
Refers #1410
https://github.com/user-attachments/assets/cbef58b7-f0c0-4a25-9039-28519df3fd46
> feat(cat-voices): automatic markdown recognition for rich text

- catalyst-gateway/tests/schemathesis_tests/Earthfile
- catalyst_voices/melos.yaml
In new [Dart 3.7](https://medium.com/dartlang/announcing-dart-3-7-bf864a1b195c) there was a change to `dart format --fix` this PR fixes issue with dart format being not supported any more
```
There is one breaking change as well. The formatter no longer supports dart format --fix. 
Instead, use dart fix to apply all the fixes that dart format could, and more.
```
N/A
-changing melos script for format-apply and format-check
- changing melos in catalyst_voices
N/A
N/A
> fix(cat-voices): Dart format in melos file after updating Dart 3.7

- catalyst_voices/apps/voices/integration_test/README.md
Added a long missing README.md file for integration tests. 
Example of how readme looks like can be seen here: https://github.com/input-output-hk/catalyst-voices/tree/1864-document-integration-tests/catalyst_voices/apps/voices/integration_test
Closes #1867
Added a readme file clearly explaining how to run tests and how to structure tests
There are no breaking changes
> test(cat-voices): Added readme file for integration tests

- catalyst_voices/apps/voices/lib/pages/discovery/sections/campaign_hero.dart
- catalyst_voices/apps/voices/lib/pages/discovery/sections/current_campaign.dart
- catalyst_voices/apps/voices/lib/widgets/campaign_timeline/campaign_timeline.dart
- catalyst_voices/apps/voices/lib/widgets/cards/pending_proposal_card.dart
Final keyword in _border for proposal_cards throws an exception while changing a theme so its needed to be deleted. 
Also added optional horizontal padding in the timeline campaign because its wasn't working on discovery page.
Minor change to foreground color in MyProposals discovery page
N/A
- remove final keyword in _border for proposals_card
- adding optional horizontal padding
- changing foreground color for MyProposals button in discovery Page.
N/A 
Before
After
N/A
> fix(cat-voices): Final keyword in _border and padding in campaign timeline

- catalyst-gateway/bin/Cargo.toml
`base64ct` crate just released a new version which requires a latest compiler `1.85` which does not work in our case.
Set a strict version of the `base64ct` transitive dep.
> fix(cat-gateway): Set a strict version of the `base64ct` transitive dep

- catalyst-gateway/bin/src/service/common/responses/code_412_precondition_failed.rs
Fix `ContentErrorDetail`  OpenApi definition, replace using `nullable` with `skip_serializing_if_is_none`
> fix(cat-gateway): Fix `ContentErrorDetail` OpenApi definition

- catalyst-gateway/Earthfile
- catalyst-gateway/bin/src/cli.rs
- catalyst-gateway/bin/src/service/api/mod.rs
- catalyst-gateway/bin/src/settings/cassandra_db.rs
- catalyst-gateway/bin/src/settings/chain_follower.rs
- catalyst-gateway/bin/src/settings/mod.rs
- catalyst-gateway/bin/src/settings/str_env_var.rs
Cleanup service settings, fix an issue when calling `cat-gateway docs` cli option service address in OpenAPI docs set incorrectly.
- Moved definitions of `ADDRESS` and `SERVER_NAME` under the `EnvVars` structure as the rest of the service settings.
- Improved definition of duration based settings.
- Renamed `new_as` to `new_as_int`, to improve clarity what does this function do.
> fix(cat-gateway): Move `ADDRESS` and `SERVER_NAME` settings to be only configured from env vars

- catalyst_voices/apps/voices/lib/pages/discovery/sections/current_campaign.dart
- catalyst_voices/apps/voices/lib/pages/discovery/state_selectors/most_recent_proposals_selector.dart
- catalyst_voices/packages/internal/catalyst_voices_blocs/lib/src/discovery/discovery_cubit.dart
Keyword late throw an exception if stream subscription was not set before subscribing to it!
N/A
- remove keyword late
- making sure that loading state is disabled
N/A
N/A
N/A
> fix(cat-voices): most recent proposal stream

- catalyst_voices/packages/internal/catalyst_voices_models/lib/src/user/catalyst_id.dart
- catalyst_voices/packages/internal/catalyst_voices_models/test/user/catalyst_id_test.dart
- catalyst_voices/packages/internal/catalyst_voices_repositories/lib/src/signed_document/signed_document_manager_impl.dart
- catalyst_voices/packages/internal/catalyst_voices_repositories/test/src/signed_document/signed_document_manager_test.dart
- catalyst_voices/packages/internal/catalyst_voices_services/lib/src/auth/auth_service.dart
- catalyst_voices/packages/internal/catalyst_voices_services/lib/src/proposal/proposal_service.dart
- catalyst_voices/packages/internal/catalyst_voices_services/lib/src/registration/registration_service.dart
- catalyst_voices/packages/internal/catalyst_voices_shared/lib/src/user/dummy_catalyst_id_factory.dart
Fixes role0Key bytes in CatalystId to make sure it uses 32 bytes public key and not the extended public key (64 bytes).
> fix(cat-voices): catalyst ID bytes length

- catalyst_voices/packages/internal/catalyst_voices_repositories/lib/src/signed_document/signed_document_manager_impl.dart
- catalyst_voices/packages/libs/catalyst_cose/lib/src/cose_sign.dart
- catalyst_voices/packages/libs/catalyst_cose/lib/src/cose_sign1.dart
cat-gateway will allow to skip COSE_SIGN tag and alg header and will assume default values for signed documents. The PR removes these from the signed documents that frontend generates to save data transfer/storage.
> feat(cat-voices): remove alg and tag from cose sign structure

- catalyst_voices/packages/internal/catalyst_voices_models/lib/src/signed_document/signed_document.dart
- catalyst_voices/packages/internal/catalyst_voices_repositories/lib/src/signed_document/signed_document_manager_impl.dart
- catalyst_voices/packages/internal/catalyst_voices_repositories/test/src/signed_document/signed_document_manager_test.dart
Extracts the CatalystID from COSE_SIGN signature protected headers (kid).
> feat(cat-voices): extract catalyst id from signed document

- catalyst-gateway/bin/Cargo.toml
- catalyst-gateway/bin/src/service/api/documents/templates/mod.rs
- catalyst-gateway/bin/src/service/common/auth/rbac/scheme.rs
Bump cat-libs version to most recent one.
- It removes unused and unneeded Catalyst Signed Docs metadata `alg` field
- It also allows to submit tagged and untagged Catalyst Signed Docs encoded bytes
> feat(cat-gateway): Bump cat-libs version

- catalyst_voices/apps/voices/lib/pages/category/category_page.dart
- catalyst_voices/apps/voices/lib/pages/discovery/discovery_page.dart
Making text selectable on Discovery and Category Detail Page. 
Closes #1903 
Closes #1902 
As we don't have good approach to make whole application selectable I'm wrapping single pages into selection area.
N/A
N/A
N/A
> feat(cat-voices): Make text selectable on Discovery and Category Page

- catalyst-gateway/bin/Cargo.toml
A new release of the `orx-iterable` transitive crate have a breaking change, which breaks our compilation.
> fix(cat-gateway): Fix `cat-gateway` build.

- catalyst_voices/apps/voices/lib/common/typedefs.dart
- catalyst_voices/apps/voices/lib/pages/overall_spaces/space/discovery_overview.dart
- catalyst_voices/apps/voices/lib/pages/overall_spaces/space/user_proposal_selectors/discovery_overview_proposal_selector.dart
- catalyst_voices/apps/voices/lib/pages/overall_spaces/space/user_proposal_selectors/user_proposal_selectors.dart
- catalyst_voices/apps/voices/lib/pages/overall_spaces/space/user_proposal_selectors/user_proposals_selector_widgets.dart
- catalyst_voices/apps/voices/lib/pages/overall_spaces/space/user_proposal_selectors/workspace_overview_proposal_selector.dart
- catalyst_voices/apps/voices/lib/pages/overall_spaces/space/workspace_overview.dart
- catalyst_voices/apps/voices/lib/pages/overall_spaces/spaces_overview_list_view.dart
- catalyst_voices/apps/voices/lib/pages/spaces/drawer/guest_menu.dart
- catalyst_voices/apps/voices/lib/pages/spaces/spaces_shell_page.dart
- catalyst_voices/apps/voices/lib/widgets/cards/small_proposal_card.dart
- catalyst_voices/apps/voices/test/widgets/cards/small_proposal_card_test.dart
- catalyst_voices/packages/internal/catalyst_voices_blocs/lib/src/workspace/workspace_bloc.dart
- catalyst_voices/packages/internal/catalyst_voices_blocs/lib/src/workspace/workspace_event.dart
- catalyst_voices/packages/internal/catalyst_voices_blocs/lib/src/workspace/workspace_state.dart
- catalyst_voices/packages/internal/catalyst_voices_localization/lib/l10n/intl_en.arb
- catalyst_voices/packages/internal/catalyst_voices_models/lib/src/proposal/proposal_version.dart
This pr adds users proposals in proposals and overall spaces 
Closes #1687 
-adding two bloc selectors to tap into a stream of users proposals
N/A
> feat(cat-voices): integrate user proposals into drawer and overall spaces

- Earthfile
- catalyst-gateway/Earthfile
- catalyst-gateway/event-db/Earthfile
- catalyst-gateway/tests/Earthfile
- catalyst-gateway/tests/api_tests/Earthfile
- catalyst_voices/Earthfile
- catalyst_voices/packages/libs/catalyst_cardano/catalyst_cardano/wallet-automation/Earthfile
- catalyst_voices/packages/libs/catalyst_key_derivation/Earthfile
- catalyst_voices/packages/libs/catalyst_key_derivation/pubspec.yaml
- catalyst_voices/packages/libs/catalyst_key_derivation/rust/Cargo.toml
- catalyst_voices/packages/libs/catalyst_key_derivation/rust/Earthfile
- catalyst_voices/utilities/uikit_example/Earthfile
- docs/Earthfile
- utilities/docs-preview/Earthfile
Bumping `flutter_rust_bridge` to the most recent one to fix the following compiling issue
```
Compiling catalyst_key_derivation v0.1.0 (/work/rust)
flutter-rust-bridge+code-generator *failed* | error: this function definition involves an argument of type `()` which is affected by the wasm ABI transition
flutter-rust-bridge+code-generator *failed* |     --> src/frb_generated.rs:1677:5
flutter-rust-bridge+code-generator *failed* |      |
flutter-rust-bridge+code-generator *failed* | 1677 |     flutter_rust_bridge::frb_generated_boilerplate_web!();
flutter-rust-bridge+code-generator *failed* |      |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
flutter-rust-bridge+code-generator *failed* |      |
flutter-rust-bridge+code-generator *failed* |      = warning: this was previously …
```
> fix(cat-gateway): Fix `catalyst_key_derivation` build

- catalyst_voices/apps/voices/lib/widgets/modals/proposals/create_new_proposal_dialog.dart
- catalyst_voices/packages/internal/catalyst_voices_blocs/lib/src/proposal_builder/new_proposal/new_proposal_cubit.dart
- catalyst_voices/packages/internal/catalyst_voices_blocs/lib/src/proposal_builder/proposal_builder_bloc.dart
Proposal editor works in a way that if a signed (published) document is opened and user makes an edit a new (draft) version is created. However that (new) version was not being reflected in the version history.
This PR makes sure that the new version is added to the history.
Additionally handles errors when creating new proposals from the dialog.
> fix(cat-voices): handle new versions created by the proposal builder

- catalyst_voices/apps/voices/lib/pages/overall_spaces/back_fab.dart
- catalyst_voices/apps/voices/lib/pages/spaces/spaces_shell_page.dart
- Makes sure campaign admin tools are disabled in release builds.
- Makes sure treasury space cannot be accessed.
- Hidden hamburger menu button when account is locked (UX request).
Closes #1954
> feat(cat-voices): hide admin functionality

- catalyst-gateway/bin/src/service/api/documents/common/mod.rs
- catalyst-gateway/bin/src/service/api/documents/put_document/mod.rs
- catalyst-gateway/bin/src/service/common/auth/rbac/scheme.rs
- catalyst-gateway/bin/src/service/common/auth/rbac/token.rs
- catalyst-gateway/bin/src/service/common/responses/mod.rs
- catalyst-gateway/tests/api_tests/integration/test_signed_doc.py
Disable Catalyst Signed Documents integration tests for CI right now. 
They will require a valid RBAC registration which means a completed index of the Cardano blockchain.
> feat(cat-gateway): Disable Catalyst Signed Documents integration tests

- catalyst-gateway/tests/schemathesis_tests/hooks/hooks.py
Fixing schemathesis CI failure causing by [`hypothesis.HealthCheck.nested_given`](https://hypothesis.readthedocs.io/en/latest/reference/api.html#hypothesis.HealthCheck)
```
./c/t/schemathesis_tests+test-ci-schemathesis |     hypothesis.errors.FailedHealthCheck: Nesting @given tests results in quadratic generation and shrinking behavior and can usually be more cleanly expressed by replacing the inner function with an st.data() parameter on the outer @given.
./c/t/schemathesis_tests+test-ci-schemathesis |     See https://hypothesis.readthedocs.io/en/latest/reference/api.html#health-checks for more information about this. If you want to disable just this health check, add HealthCheck.nested_given to the suppress_health_check settings for this test.
```
> fix(cat-gateway): Fix hypothesis.HealthCheck.nested_given error

- catalyst_voices/apps/voices/lib/app/view/app_content.dart
- catalyst_voices/apps/voices/lib/app/view/app_session_listener.dart
- catalyst_voices/apps/voices/lib/routes/app_router.dart
This PR resolves issue when user lock the app and was not redirected to Discovery Page
Closes #2201
- making AppRoute global key public to be able to call it from GlobalStateListener
N/A
N/A
N/A
> fix(cat-voices): When user locks app should be redirected to Discovery Page

- catalyst_voices/packages/internal/catalyst_voices_services/lib/src/user/user_service.dart
- catalyst_voices/packages/internal/catalyst_voices_services/test/src/user/user_service_test.dart
Make sure to update account after recovery to apply the latest password.
Closes #2150
> fix(cat-voices): password not updating after account recovery

- catalyst_voices/apps/voices/lib/pages/registration/widgets/export_catalyst_key_confirm_dialog.dart
Changes "Cancel anyway" to "Cancel" in a dialog for exporting seed phrase.
Closes #2188
> fix(cat-voices): cancel button text

- catalyst_voices/packages/internal/catalyst_voices_localization/lib/l10n/intl_en.arb
We switch from download keychain to export keychain for more clarity for users
Closes #2191
-change downloaded to exported
N/A
N/A
N/A
> fix(cat-voices): update keychain seed phrase confirmation message for clarity in instructions

- catalyst_voices/apps/voices/lib/pages/account/widgets/account_roles_tile.dart
Hide the button to add roles if all of them are added
Closes #2182
> fix(cat-voices): hide the button to add roles if all of them are added

- catalyst_voices/apps/voices/lib/dependency/dependencies.dart
- catalyst_voices/apps/voices/lib/widgets/modals/proposals/create_new_proposal_dialog.dart
- catalyst_voices/packages/internal/catalyst_voices_blocs/lib/src/proposal_builder/new_proposal/new_proposal_cubit.dart
- catalyst_voices/packages/internal/catalyst_voices_blocs/lib/src/proposal_builder/new_proposal/new_proposal_state.dart
- catalyst_voices/packages/internal/catalyst_voices_models/lib/src/user/account.dart
A common logic around handling missing proposer role in new proposal dialog.
The actual design for `Proposer role missing` state will be implemented later when it becomes available, the PR implements the logic part (checking whether the user has proposer role, etc).
Refers #2213
> fix(cat-voices): create new proposal dialog - handle missing proposer role

- catalyst_voices/apps/voices/lib/pages/registration/create_keychain/stage/seed_phrase_check_panel.dart
- catalyst_voices/apps/voices/lib/pages/registration/recover/seed_phrase/seed_phrase_input_panel.dart
- catalyst_voices/apps/voices/lib/pages/registration/upload_seed_phrase_dialog.dart
This pr make proper workflow for close button in upload keychain dialog (earlier when user cancel, then invalid keychain dialog happen when user just wanted to stop the action) 
Closes #2220
N/A
N/A
N/A
N/A
> fix(cat-voices): proper cancel workflow for update keychain

- catalyst_voices/apps/voices/lib/pages/registration/create_keychain/stage/unlock_password_panel.dart
- catalyst_voices/apps/voices/lib/pages/registration/recover/seed_phrase/unlock_password_panel.dart
- catalyst_voices/apps/voices/lib/pages/registration/widgets/unlock_password_form.dart
Adding onSubmitted method in confirm passowrd to trigger next step in registration process
Closes #2204
N/A
N/A
N/A
N/A
> refactor(cat-voices): adding onSubmitted method on confirm password in registration dialog

- catalyst-gateway/bin/src/service/api/cardano/rbac/mod.rs
Enable `rbac/registration` endpoint for schemathesis validation, make it `v1`
Closes https://github.com/input-output-hk/catalyst-voices/issues/2272
> feat(cat-gateway): Make `rbac/registration`  `v1`

- catalyst_voices/apps/voices/pubspec.yaml
- catalyst_voices/melos.yaml
- catalyst_voices/utilities/poc_local_storage/pubspec.yaml
We inspirance a little problem among different version of go_router so to resolve it we update go_router for 14.0.2 to 14.8.0.
N/A
- adding go_router to melos.yaml to make sure every pubspec in out repo have the same version
N/A
N/A
N/A
> chore(cat-voices): update go_router to 14.8.0 in melos

- catalyst_voices/apps/voices/lib/app/view/app_content.dart
- catalyst_voices/apps/voices/lib/app/view/app_mobile_access_restriction.dart
This PR changes the order of rendering the widget to make sure that the mobile restriction widget is render properly.
N/A
- change order of the widgets
N/A
N/A
N/A
> fix(cat-voices): Splash screen should be above mobile restriction widget

- catalyst-gateway/bin/Cargo.toml
[`local-ip-address`](https://crates.io/crates/local-ip-address) just release a new version `0.6.4` which has some breaking changes. Lock the version to `0.6.3`
> fix(cat-gateway): lock local-ip-address to `0.6.3`

- catalyst_voices/apps/voices/lib/widgets/text_field/voices_text_field.dart
Makes helper text two lines by default.
Make helper text two lines so registration email helper text is visible.
> fix(cat-voices): Two lines helper text

- catalyst_voices/apps/voices/lib/pages/workspace/proposal_menu_action_button.dart
- catalyst_voices/apps/voices/lib/widgets/cards/proposal/workspace_proposal_card.dart
- catalyst_voices/apps/voices/lib/widgets/cards/proposal_iteration_history_card.dart
- catalyst_voices/packages/internal/catalyst_voices_localization/lib/l10n/intl_en.arb
- catalyst_voices/packages/internal/catalyst_voices_models/lib/src/proposal/proposal.dart
This PR. makes that when user have new local iteration he cant edit the published one until the local one is deleted.
#2290
- adding new method to show warning snackbar
N/A
In the video snackbar is blue but its yellow. Video was recorded before this change
https://github.com/user-attachments/assets/322b54d5-433f-49cb-8f94-bb59d439090a
N/A
> feat(cat-voices): cant edit when new local iteration is created

- catalyst_voices/melos.yaml
- catalyst_voices/packages/internal/catalyst_voices_brands/test/src/catalyst_voices_brands_test.dart
Enable web unit tests for `catalyst_voices_assets` package.
This PR does not really resolve root problem as described in issue but since issue was reported we've moved template json tests from depending on assets file to directly from `/docs` in #2298 and we can enable back tests for this package.
Resolves #1979 
- no longer ignoring unit tests for `catalyst_voices_assets`
- make sure brand widget unit tests are using non system theme mode
> fix(cat-voices): enable unit web tests for catalyst_voices_assets

- catalyst_voices/apps/voices/lib/pages/account/account_page.dart
As the account page is outside of the go router shell its need its own end drawer with opportunities.
#2428
- adding new end drawer
N/A
N/A
> fix(cat-voices): missing opportunities drawer in account page

- catalyst_voices/apps/voices/lib/widgets/pagination/layouts/paginated_grid_view.dart
Hide pagination controls when less then 1 page available
Fixes #2415
> chore(cat-voices): hide pagination controls when less then one page available

- catalyst_voices/apps/voices/lib/widgets/modals/voices_desktop_dialog.dart
Positions all dialogs in center relative to screen. (Not parent).
This means all "big" dialogs moves from `topCenter` just to `center`. 
Fixes #2405
> fix(cat-voices): center dialogs

- catalyst_voices/apps/voices/lib/pages/discovery/sections/stay_involved.dart
- catalyst_voices/apps/voices/lib/pages/discovery/state_selectors/campaign_categories_state_selector.dart
- catalyst_voices/apps/voices/lib/pages/discovery/state_selectors/current_campaign_selector.dart
- catalyst_voices/apps/voices/lib/pages/discovery/state_selectors/most_recent_proposals_selector.dart
- catalyst_voices/packages/internal/catalyst_voices_blocs/lib/src/discovery/discovery.dart
- catalyst_voices/packages/internal/catalyst_voices_blocs/lib/src/discovery/discovery_cubit.dart
- catalyst_voices/packages/internal/catalyst_voices_blocs/lib/src/discovery/discovery_state.dart
Making sure new state is not emitted after bloc is closed
Only relevant changes are adding `if (!isClosed)` in `DiscoveryCubit`. In future i'll extract this behaviour into abstract class
> fix(cat-voices): do not emit new state when closed

- catalyst_voices/packages/internal/catalyst_voices_blocs/lib/src/proposals/proposals_cubit.dart
- catalyst_voices/packages/internal/catalyst_voices_repositories/lib/src/database/dao/proposals_dao.dart
- catalyst_voices/packages/internal/catalyst_voices_repositories/lib/src/proposal/proposal_repository.dart
- Makes sure that hidden proposals are excluded in `My Proposals` tab.
- Makes sure that `ProposalCubit.cache` has correctly assigned `author`.
Refers #2469
> fix(cat-voices): loading my proposals

- catalyst_voices/apps/voices/lib/widgets/document_builder/viewer/document_property_builder_viewer.dart
Allows multiline for markdown in ProposalBuilder view mode
Fixes #2481 
Allows markdown text to be multiline when viewing in ProposalBuilder 
Before
https://github.com/user-attachments/assets/b5a9e407-2437-4039-b623-f9046df6fb45
After
> fix(cat-voices): missing multiline for MarkdownText

- catalyst_voices/packages/internal/catalyst_voices_blocs/lib/src/proposal/proposal_cubit.dart
- catalyst_voices/packages/internal/catalyst_voices_models/lib/src/document/specialized/proposal_document.dart
This PR sets proper autho name for proposal in proposal cards and proposal viewer in Profile Section.
N/A
- adding getter for CatalystId
- changing other of fallback for getter for authorName (firstly we try to get name from CatalystId)
N/A
Now:
Before
N/A
> feat(cat-voices): get author name of proposal firstly from CatalystId

- catalyst_voices/apps/voices/lib/widgets/user/profile_avatar.dart
A little change in padding to resolve issue with cutted of bottom of letter in voices avatar in [proposal.viewer]
Part of #2505
- change of padding
N/A
After: 
Before:
N/A
> fix(cat-voices): cut character in avatar - proposal viewer

- catalyst_voices/apps/voices/lib/pages/overall_spaces/space/user_proposal_selectors/discovery_overview_proposal_selector.dart
- catalyst_voices/packages/internal/catalyst_voices_blocs/lib/src/workspace/workspace_state.dart
- catalyst_voices/packages/internal/catalyst_voices_localization/lib/l10n/intl_en.arb
- catalyst_voices/packages/internal/catalyst_voices_models/lib/src/proposal/proposal.dart
- catalyst_voices/packages/internal/catalyst_voices_models/lib/src/proposal/proposal_enums.dart
- catalyst_voices/packages/internal/catalyst_voices_models/test/proposal/proposal_enums_test.dart
- Let's remove the (x/x)
- Show final proposals first
- Sort finals by newest in the top.
- Than show draft proposals
- Sort Drafts by newest in the top.
> fix(cat-voices): proposals limit in navigation rail

- catalyst_voices/apps/voices/pubspec.yaml
- catalyst_voices/melos.yaml
Reverts the [workaround for win32](https://github.com/jonataslaw/get_cli/issues/263) which is no longer needed.
https://github.com/jonataslaw/get_cli/issues/263
> chore(cat-voices): revert win32 workaround

- catalyst_voices/apps/voices/integration_test/suites/account_test.dart
- catalyst_voices/apps/voices/integration_test/suites/app_test.dart
- catalyst_voices/apps/voices/integration_test/suites/discovery_test.dart
- catalyst_voices/apps/voices/integration_test/suites/onboarding_restore_test.dart
- catalyst_voices/apps/voices/integration_test/suites/onboarding_test.dart
- catalyst_voices/apps/voices/integration_test/suites/proposals_test.dart
- catalyst_voices/apps/voices/lib/configs/bootstrap.dart
- catalyst_voices/packages/internal/catalyst_voices_blocs/lib/src/registration/registration_cubit.dart
- catalyst_voices/packages/internal/catalyst_voices_blocs/test/session/session_cubit_test.dart
- catalyst_voices/packages/internal/catalyst_voices_models/lib/src/blockchain/blockchain_slot_config.dart
- catalyst_voices/packages/internal/catalyst_voices_models/lib/src/config/app_config.dart
- catalyst_voices/packages/internal/catalyst_voices_repositories/lib/src/config/app_config_factory.dart
- catalyst_voices/packages/internal/catalyst_voices_repositories/lib/src/dto/config/remote_blockchain_config.dart
- catalyst_voices/packages/internal/catalyst_voices_repositories/test/fixture/configs.dart
- catalyst_voices/packages/internal/catalyst_voices_repositories/test/src/config/config_repository_test.dart
- catalyst_voices/packages/internal/catalyst_voices_services/lib/src/blockchain/blockchain_service.dart
- catalyst_voices/packages/internal/catalyst_voices_services/lib/src/registration/registration_service.dart
- catalyst_voices/packages/internal/catalyst_voices_services/test/src/blockchain/blockchain_service_test.dart
- catalyst_voices/packages/internal/catalyst_voices_services/test/src/user/user_service_test.dart
- catalyst_voices/packages/internal/catalyst_voices_shared/test/src/keychain/vault_keychain_provider_test.dart
- config/dev/config.json
- config/preprod/config.json
- config/prod/config.json
Makes blockchain slot number configurable via remote config
Resolves #2511 
Extends blockchain config with slot number
> feat(cat-voices): blockchain slot number config

- catalyst-gateway/bin/src/db/index/session.rs
Added missing `#[source]` for the `CassandraSessionError` variants, to respect this comment https://github.com/input-output-hk/catalyst-voices/pull/2492#discussion_r2081499345.
> feat(cat-gateway): Missing `thiserror` `#[source]` directivies

- catalyst_voices/apps/voices/lib/common/formatters/date_formatter.dart
- catalyst_voices/apps/voices/lib/pages/discovery/sections/stay_involved.dart
- catalyst_voices/packages/internal/catalyst_voices_repositories/lib/src/database/dao/drafts_dao.dart
- catalyst_voices/packages/internal/catalyst_voices_repositories/lib/src/database/query/jsonb_expressions.dart
- catalyst_voices/packages/internal/catalyst_voices_repositories/lib/src/database/table/documents_metadata.dart
- catalyst_voices/packages/libs/catalyst_analysis/lib/analysis_options.yaml
As we transition to 100 char long line we don't longer need linter for 80 char long line
N/A
- Remove linter rule
- Remove ignore comments for that rule
N/A
N/A
N/A
> chore(cat-voices): remove linter 80 char long line

- catalyst-gateway/bin/src/rbac_cache/cache.rs
Disallow [reusing public keys in RBAC chains](https://github.com/input-output-hk/catalyst-libs/blob/main/rust/rbac-registration/examples.md#reusing-a-public-key).
Closes https://github.com/input-output-hk/catalyst-voices/issues/2561.
> feat(cat-gateway): Disallow reusing public keys in RBAC chains

- catalyst_voices/packages/internal/catalyst_voices_blocs/lib/src/proposal_builder/new_proposal/new_proposal_cubit.dart
- catalyst_voices/packages/internal/catalyst_voices_view_models/lib/src/proposal/proposal_title.dart
Additinal requirements for new proposal dialog:
If user checks the boxes then selects a different category, the boxes are cleared.
After inputting minimum of 3 characters in the Title, button activates
Closes #2608
- adding min length validation
- Resetting check boxes if the selected category changes.
N/A
N/A
N/A
> feat(cat-voices): min title length validation and recheck checkboxes 

- catalyst_voices/apps/voices/lib/widgets/modals/proposals/share_proposal_dialog.dart
- catalyst_voices/apps/voices/lib/widgets/modals/voices_share_dialog.dart
This PR makes the snackbar visible at the level of the dialog not under the overlay
Closes #2619
-adding new snackbarmesseger and scaffold to show snackbar at proper level
N/A
N/A
> feat(cat-voices): show snackbar at the same level of share dialog

- catalyst_voices/apps/voices/lib/pages/proposal/proposal_page.dart
- catalyst_voices/apps/voices/lib/pages/proposal/widget/proposal_navigation_controls.dart
- catalyst_voices/apps/voices/lib/widgets/app_bar/voices_app_bar.dart
- catalyst_voices/apps/voices/lib/widgets/buttons/navigation_back.dart
- catalyst_voices/apps/voices/lib/widgets/buttons/voices_buttons.dart
- catalyst_voices/apps/voices/lib/widgets/widgets.dart
Moved proposal page "back to list" to the AppBar because it was hidden by sticky header when scrolled. 
Resolves #2690
> feat(cat-voices): move proposal back arrow to AppBar

- catalyst-gateway/bin/src/service/api/documents/templates/data.rs
- catalyst-gateway/bin/src/service/api/documents/templates/docs/category/f14_concepts.schema.json
- catalyst-gateway/bin/src/service/api/documents/templates/docs/category/f14_developers.schema.json
- catalyst-gateway/bin/src/service/api/documents/templates/docs/category/f14_ecosystem.schema.json
- catalyst-gateway/bin/src/service/api/documents/templates/docs/category/f14_partner_product.schema.json
- catalyst-gateway/bin/src/service/api/documents/templates/docs/f14_proposal_template.schema.json
- catalyst-gateway/bin/src/service/api/documents/templates/docs/proposal/f14_concept.schema.json
- catalyst-gateway/bin/src/service/api/documents/templates/docs/proposal/f14_developer.schema.json
- catalyst-gateway/bin/src/service/api/documents/templates/docs/proposal/f14_ecosystem.schema.json
- catalyst-gateway/bin/src/service/api/documents/templates/docs/proposal/f14_partner_product.schema.json
- catalyst-gateway/bin/src/service/api/documents/templates/docs/proposal/f14_proposal_template.schema.json
- docs/src/architecture/08_concepts/document_templates/proposal/F14-Generic/0194d492-1daa-716f-a04e-f422f08a99dc.schema.json
- docs/src/architecture/08_concepts/document_templates/proposal/F14-Generic/0194d492-1daa-7371-8bd3-c15811b2b063.schema.json
- docs/src/architecture/08_concepts/document_templates/proposal/F14-Generic/0194d492-1daa-75b5-b4a4-5cf331cd8d1a.schema.json
- docs/src/architecture/08_concepts/document_templates/proposal/F14-Generic/0194d492-1daa-79c7-a222-2c3b581443a8.schema.json
Proposal template ref were named with category id instead of the proper proposal category id. 
https://github.com/input-output-hk/catalyst-voices/blob/main/catalyst_voices/packages/internal/catalyst_voices_models/lib/src/document/constant_documents_refs.dart
N/A
- named proposal template files with proper category proposal id 
N/A
N/A
N/A
> fix(cat-voices): assign proposal category id instead of category id

- catalyst_voices/apps/voices/lib/pages/registration/registration_dialog.dart
- catalyst_voices/packages/internal/catalyst_voices_blocs/lib/src/registration/cubits/keychain_creation_cubit.dart
- catalyst_voices/packages/internal/catalyst_voices_blocs/lib/src/registration/registration_cubit.dart
- catalyst_voices/packages/internal/catalyst_voices_blocs/test/session/session_cubit_test.dart
- catalyst_voices/packages/internal/catalyst_voices_localization/lib/l10n/intl_en.arb
- catalyst_voices/packages/internal/catalyst_voices_models/lib/src/registration/exception/registration_exception.dart
- catalyst_voices/packages/internal/catalyst_voices_models/lib/src/registration/registration_progress.dart
- catalyst_voices/packages/internal/catalyst_voices_services/lib/src/registration/registration_service.dart
- catalyst_voices/packages/internal/catalyst_voices_view_models/lib/src/registration/exception/localized_registration_exception.dart
Recovering local keychain while finishing registration with keychain already created
Fixes #2724
> fix(cat-voices): recovering keychain while finishing registration

- catalyst_voices/packages/internal/catalyst_voices_repositories/lib/src/dto/user/catalyst_id_public_ext.dart
- catalyst_voices/packages/internal/catalyst_voices_repositories/test/src/dto/user/catalyst_id_public_ext_test.dart
Decodes correctly account public profile username
Fixes #2738
> fix(cat-voices): decode account public id username

- catalyst_voices/apps/voices/lib/app/view/video_cache/app_video_manager.dart
- catalyst_voices/apps/voices/lib/widgets/video/video_player.dart
For some reason when VideoPlayer widget is disposed and recreated, it won't interact withthe  previously initialized video controller.
#2722
- adding reinitialization logic
N/A
https://github.com/user-attachments/assets/f979e0ba-95f9-49cd-af43-05a1ff655bc4
N/A
> fix(cat-voices): freezed video

- catalyst_voices/apps/voices/lib/pages/proposal_builder/proposal_builder_document_widgets.dart
- catalyst_voices/apps/voices/lib/widgets/list/category_requirements_list.dart
Design resigned from the additional (different color) in the proposal builder for the category dos and don'ts
Resolves #2778
> chore(cat-voices): remove unnecessary colour from category do's and don'ts

- catalyst-gateway/bin/Cargo.toml
Bumped cat-libs dependencies with the latest release.
https://github.com/input-output-hk/catalyst-libs/releases/tag/r20250619-00
Main update is brining new mithril downloader logging https://github.com/input-output-hk/catalyst-libs/pull/361
Closes https://github.com/input-output-hk/catalyst-voices/issues/1379
> feat(cat-gateway): Bump cat-libs to r20250619-00

- catalyst-gateway/bin/src/db/index/queries/rbac/get_catalyst_id_from_public_key.rs
- catalyst-gateway/bin/src/db/index/queries/rbac/get_catalyst_id_from_stake_address.rs
- catalyst-gateway/bin/src/db/index/queries/rbac/get_catalyst_id_from_transaction_id.rs
- catalyst-gateway/bin/src/metrics/mod.rs
- catalyst-gateway/bin/src/metrics/rbac_cache.rs
- catalyst-gateway/bin/src/rbac/chains_cache.rs
- catalyst-gateway/bin/src/rbac/mod.rs
- catalyst-gateway/bin/src/rbac_cache/mod.rs
- catalyst-gateway/bin/src/settings/mod.rs
Update RBAC cache(s) metric. For now we have the following metrics per cache:
- hits
- misses
- size
Closes https://github.com/input-output-hk/catalyst-voices/issues/2848.
> feat(cat-gateway): Update RBAC cache metrics

- catalyst-gateway/bin/src/service/common/types/cardano/ada_value.rs
- catalyst-gateway/bin/src/service/common/types/cardano/asset_value.rs
- Fixed two `saturating_add` methods for `AssetValue` and `AdaValue` types. Was incorrect logging of addition overflow
> fix(cat-gateway): Fixing incorrect `error!` message logging for `saturating_add` methods

- catalyst-gateway/bin/src/db/index/block/roll_forward.rs
Invalidate RBAC volatile caches on rollbacks.
Closes https://github.com/input-output-hk/catalyst-voices/issues/2606.
> feat(cat-gateway): Invalidate RBAC caches on rollbacks

- catalyst-gateway/bin/src/cardano/mod.rs
- catalyst-gateway/bin/src/service/utilities/health/start.rs
- Fixed issue for notifying and setting flag `INITIAL_IMMUTABLE_FOLLOWER_TIP_REACHED` and emitting event `SyncImmutableChainCompleted`
- Cleaned logging 
Closes #2945
> fix(cat-gateway): Correct `immutable_tip` notifying behaviour, when index-db is already indexed

- catalyst_voices/apps/voices/lib/widgets/document_builder/value/single_grouped_tag_selector_widget.dart
- catalyst_voices/packages/internal/catalyst_voices_localization/lib/l10n/intl_en.arb
Title in edit state and in view mode is not the same. Title in edit state was taken from intl files and not from the json schema for Tag widget
N/A
N/A
N/A
Befor fix
https://github.com/user-attachments/assets/8e6c2028-2338-400e-a4b2-343ce037ea5f
N/A
> fix(cat-voices): title in edit state for tag widget in proposal builder

- catalyst_voices/apps/voices/lib/app/view/app_content.dart
- catalyst_voices/apps/voices/lib/app/view/app_mobile_access_restriction.dart
- catalyst_voices/apps/voices/lib/common/constants/constants.dart
- catalyst_voices/apps/voices/lib/pages/proposal/proposal_content.dart
- catalyst_voices/apps/voices/lib/pages/proposal/proposal_page.dart
- catalyst_voices/apps/voices/lib/pages/proposal/snack_bar/viewing_older_version_snack_bar.dart
- catalyst_voices/apps/voices/lib/pages/proposal/tiles/proposal_metadata_tile.dart
- catalyst_voices/apps/voices/lib/pages/proposal/tiles/proposal_overview_tile.dart
- catalyst_voices/apps/voices/lib/pages/proposal/widget/proposal_app_closed.dart
- catalyst_voices/apps/voices/lib/pages/proposal/widget/proposal_header.dart
- catalyst_voices/apps/voices/lib/pages/proposal/widget/proposal_sidebars.dart
- catalyst_voices/apps/voices/lib/widgets/app_bar/voices_app_bar.dart
- catalyst_voices/packages/internal/catalyst_voices_localization/lib/l10n/intl_en.arb
- catalyst_voices/packages/internal/catalyst_voices_shared/lib/src/platform_aware_builder/platform_aware_builder.dart
Adding read view mode to proposal viewer
Closes #2607 
- overrride app restriction for proposal view route
N/A
App open, mobile view:
https://github.com/user-attachments/assets/cc14977d-9de6-444a-bd9f-046b25f6d4b2
App closed mobile view:
https://github.com/user-attachments/assets/cd2d3206-a34f-4a55-a98d-fc73a291cf39
App closed desktop view:
https://github.com/user-attachments/assets/36e6dd14-514c-446f-b0b8-eff2823dbc94
N/A
> feat(cat-voices): read only mode proposal view

- catalyst-gateway/bin/src/db/index/schema/cql/rbac_registration.cql
- catalyst-gateway/bin/src/db/index/schema/mod.rs
- catalyst-gateway/bin/src/metrics/rbac.rs
- catalyst-gateway/bin/src/rbac/get_chain.rs
- catalyst-gateway/bin/src/rbac/validation.rs
- catalyst-gateway/bin/src/service/api/cardano/rbac/registrations_get/mod.rs
- catalyst-gateway/bin/src/service/common/auth/rbac/scheme.rs
- Use short form of a Catalyst ID for comparison.
- Change sorting order in the `rbac_registration` table.
Closes https://github.com/input-output-hk/catalyst-voices/issues/3124.
> fix(cat-gateway): Fix Catalyst IDs comparins in RBAC validation

- catalyst-gateway/bin/src/metrics/caches/native_assets.rs
- catalyst-gateway/bin/src/metrics/caches/txo_assets.rs
- catalyst-gateway/bin/src/metrics/chain_indexer.rs
- catalyst-gateway/bin/src/metrics/rbac.rs
Replacing `CounterVec` with more performant `IntCounterVec` prometheus metric counter.
Closes https://github.com/input-output-hk/catalyst-voices/issues/3122
> feat(cat-gateway): replace `CounterVec` with more performant `IntCounterVec`

- catalyst-gateway/bin/src/db/index/block/rbac509/mod.rs
- catalyst-gateway/bin/src/metrics/mod.rs
- catalyst-gateway/bin/src/metrics/rbac.rs
- Added a new metric counter, to track the number of invalid RBAC registrations appeared during indexing.
> feat(cat-gateway): Invalid RBAC registration metric counter

- catalyst_voices/apps/voices/lib/dependency/dependencies.dart
- catalyst_voices/packages/internal/catalyst_voices_blocs/lib/src/voting/voting_cubit.dart
- catalyst_voices/packages/internal/catalyst_voices_models/lib/src/proposals/proposals_count.dart
- catalyst_voices/packages/internal/catalyst_voices_services/lib/src/proposal/proposal_service.dart
- catalyst_voices/packages/internal/catalyst_voices_services/test/src/proposal/proposal_service_test.dart
This PR adds mocked voted on proposals (they are stored in cache so every reset of the app lose track of voted proposals. This is intended behavior as we wait for backend integration.
Closes #3213 
- adding watching on voted on proposals
N/A
https://github.com/user-attachments/assets/98e3d6f4-d23d-4548-bd46-60b0ea49658d
N/A
> feat(cat-voices):  voted on mocked proposals

- catalyst_voices/apps/voices/lib/dependency/dependencies.dart
- catalyst_voices/packages/internal/catalyst_voices_blocs/lib/src/proposal/proposal_cubit.dart
- catalyst_voices/packages/internal/catalyst_voices_blocs/test/session/session_cubit_test.dart
- catalyst_voices/packages/internal/catalyst_voices_models/lib/src/catalyst_voices_models.dart
- catalyst_voices/packages/internal/catalyst_voices_models/lib/src/user/account.dart
- catalyst_voices/packages/internal/catalyst_voices_models/lib/src/user/account_registration_status.dart
- catalyst_voices/packages/internal/catalyst_voices_models/lib/src/user/recovered_account.dart
- catalyst_voices/packages/internal/catalyst_voices_repositories/lib/src/dto/user/account_dto.dart
- catalyst_voices/packages/internal/catalyst_voices_repositories/lib/src/user/user_repository.dart
- catalyst_voices/packages/internal/catalyst_voices_services/lib/src/catalyst_voices_services.dart
- catalyst_voices/packages/internal/catalyst_voices_services/lib/src/registration/registration_service.dart
- catalyst_voices/packages/internal/catalyst_voices_services/lib/src/user/registration_status_poller.dart
- catalyst_voices/packages/internal/catalyst_voices_services/lib/src/user/user_service.dart
- catalyst_voices/packages/internal/catalyst_voices_services/test/src/user/user_service_test.dart
This PR extends Account model with registration status object and keeps track of it.
Fixes https://github.com/input-output-hk/catalyst-voices/issues/2936
Resolves https://github.com/input-output-hk/catalyst-internal-docs/issues/305
Added new `AccountRegistrationStatus` object with `isIndexed` and `isPersistent` fields. `isIndexed` is true when gateway returns 200 rbac endpoint.
This enables us to check if account is indexed before asking reviews API for account public profile status. 
https://github.com/user-attachments/assets/c28459d2-08f2-4f92-9c4f-4b48ae3c1966
https://github.com/user-attachments/assets/5436b8cb-bdef-4d40-8e23-355c7aeeeb7e
> feat(cat-voices): tracking registration status

- catalyst-gateway/tests/api_tests/integration/signed_doc/test_signed_doc.py
- catalyst-gateway/tests/api_tests/integration/signed_doc/test_v1_signed_doc.py
- catalyst-gateway/tests/api_tests/utils/signed_doc.py
Removes all redundant catalyst signed documents test cases, which is covered on the `catalyst-signed-doc` crate.
> chore(cat-gateway): Remove redundant signed doc integration tests code
